// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error_code.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Stardom {

  /// <summary>Holder for reflection information generated from error_code.proto</summary>
  public static partial class ErrorCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for error_code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBlcnJvcl9jb2RlLnByb3RvEgdTdGFyZG9tKtNuCglFcnJvckNvZGUSDgoK",
            "RUNfU1VDQ0VTUxAAEgsKB0VDX0ZBSUwQARIOCgpFQ19VTktOT1dOEAISEgoO",
            "RUNfQVBQX1ZFUlNJT04QAxIMCghFQ19UT0tFThAEEhIKDkVDX05PVF9QTEFZ",
            "RVJTEAUSEgoORUNfUEFSQU1fRVJST1IQBhIWChJFQ19DT05GSUdfTk9URk9V",
            "TkQQBxIUChBFQ19GRUVfTk9URU5PVUdIEAgSEwoPRUNfQ09ORklHX0VSUk9S",
            "EAkSFQoRRUNfTk9fRVhQT1JUX1RJUFMQDBITCg9FQ19OT19PUEVOX1RJTUUQ",
            "DRIaChZFQ19BQ0NPVU5UX0xPR0lOX09USEVSEA4SGAoURUNfTk9UX0lOX1dI",
            "SVRFX0xJU1QQDxIVChFFQ19DTE9TRV9SRUdJU1RFUhAQEgwKCEVDX0VNUFRZ",
            "EGMSEQoNRUNfTk9fRkFDVElPThBkEhUKEUVDX1dPUkRfU0VOU0lUSVZFEGUS",
            "FQoRRUNfTkFNRV9CRUVOX1VTRUQQZhIPCgtFQ19OT19HVUlMRBBnEhQKEEVD",
            "X05BTUVfVE9PX0xPTkcQaBIcChhFQ19DSEFMTEVOR0VfVElNRVNfTElNSVQQ",
            "aRISCg5FQ19USU1FU19MSU1JVBBqEhYKEkVDX0JVWV9USU1FU19MSU1JVBBr",
            "EhMKD0VDX1NUQUdFX0ZJTklTSBBsEhYKEkVDX1NUQUdFX05PVF9GT1VORBBt",
            "EhIKDkVDX0xFVkVMX0xJTUlUEG4SEwoPRUNfSUxMRUdBTF9JVEVNEG8SFgoS",
            "RUNfR1VJTERfSU5GTFVFTkNFEHASGAoURUNfQ09OVEVOVF9UT09fU0hPUlQQ",
            "cRIXChNFQ19DT05URU5UX1RPT19MT05HEHISFQoRRUNfQUxSRUFEWV9SRVdB",
            "UkQQcxIcChhFQ19XT1JEX1NFTlNJVElWRV9ERVRBSUwQdBIXChNFQ19ORUVE",
            "X0ZJTklTSF9UQVNLEHUSFAoQRUNfQkFHX0ZVTExfSVRFTRB2EhUKEUVDX0JB",
            "R19GVUxMX0VRVUlQEHcSFgoSRUNfQkFHX0ZVTExfREVCUklTEHgSGAoURUNf",
            "QkFHX0ZVTExfUk9MRUNBUkQQeRIXChNFQ19CQUdfRlVMTF9BVldPUktTEHoS",
            "FwoTRUNfQkFHX0ZVTExfRkFTSElPThB7EhEKDUVDX1dBUl9DQU5DRUwQfBIV",
            "ChFFQ19SRVdBUkRfQUxSRUFEWRB9EhQKD0VDX0xPR0lOX1JFUEVBVBDIARIW",
            "ChFFQ19MT0dJTl9OT19MT0dJThDKARIZChRFQ19MT0dJTl9WRVJJRllfRkFJ",
            "TBDLARIZChRFQ19DUkVBVEVfT1dOX1BMQVlFUhDMARIaChVFQ19DUkVBVEVf",
            "SURfTk9URk9VTkQQzQESGwoWRUNfTE9HSU5fQUNDT1VOVF9MSU1JVBDOARIa",
            "ChVFQ19MT0dJTl9PTkxJTkVfTElNSVQQzwESHAoXRUNfTE9HSU5fUkVHSVNU",
            "RVJfTElNSVQQ0AESFwoSRUNfUExBWUVSX05PVEZPVU5EEOkHEhQKD0VDX1BM",
            "QVlFUl9MRVZFTBDqBxIUCg9FQ19QTEFZRVJfS0FXRUkQ6wcSEwoORUNfUExB",
            "WUVSX0ZBTlMQ7AcSFQoQRUNfUFJPUF9OT1RGT1VORBDPCBIaChVFQ19QUk9Q",
            "X05VTV9OT1RFTk9VR0gQ0AgSFgoRRUNfUFJPUF9DQU5OT1RVU0UQ0QgSFwoS",
            "RUNfUFJPUF9DQU5OT1RTRUxMENIIEhoKFUVDX1BST1BfU1RVRkZfTk9UX0ZJ",
            "VBDTCBIYChNFQ19BTFJFQURZX1JFV0FSREVEENQIEhAKC0VDX0JBR19GVUxM",
            "ENUIEhcKEkVDX1BST1BfR0FJTl9MSU1JVBDWCBIWChFFQ19QUk9QX1VTRV9M",
            "SU1JVBDXCBIbChZFQ19HSUZUX0NPREVfTk9UX0VYSVNUENgIEhYKEUVDX0dJ",
            "RlRfQ09ERV9VU0VEENkIEhwKF0VDX1BST1BfVVNFX0xFVkVMX0xJTUlUENoI",
            "EhYKEUVDX0dFTV9OT1RfRU5PVUdIENsIEhUKEEVDX1JPTEVfTk9URk9VTkQQ",
            "sQkSHgoZRUNfUk9MRV9MRVZFTF9VTlFVQUxJRklFRBCyCRIcChdFQ19ST0xF",
            "X1NFWF9VTlFVQUxJRklFRBCzCRIcChdFQ19ST0xFX1BST19VTlFVQUxJRklF",
            "RBC0CRIWChFFQ19ST0xFX01BWF9MRVZFTBC1CRIfChpFQ19ST0xFX1JPTEVf",
            "QUxSRUFEWV9FWElTVBC2CRIWChFFQ19ST0xFX1VQX1BMQVlFUhC3CRIVChBF",
            "Q19ST0xFX05PX0JSRUFLELgJEhYKEUVDX1JPTEVfTk9fQVdBS0VOELkJEhcK",
            "EkVDX1JPTEVfTkVFRF9CUkVBSxC6CRIZChRFQ19ST0xFX05FWFRfUVVBTElU",
            "WRC7CRIcChdFQ19ST0xFX1JFTU9ERUxfSU5JVElBTBC8CRIZChRFQ19ST0xF",
            "X1FVQUxJVFlfUExPVBC9CRIeChlFQ19ST0xFX1FVQUxJVFlfQ0hBTExFTkdF",
            "EL4JEhoKFUVDX1JPTEVfUVVBTElUWV9QUk9QUxC/CRIcChdFQ19ST0xFX1FV",
            "QUxJVFlfTk9UX0ZJVBDACRIbChZFQ19ST0xFX0VORVJHSVpFX0xJTUlUEMEJ",
            "EiAKG0VDX1JPTEVfRU5FUkdJWkVfTk9UX0VOT1VHSBDCCRIZChRFQ19ST0xF",
            "X1BPU19OT1RBTExPVxCVChIYChNFQ19ST0xFX1BPU19BTFJFQURZEJYKEhsK",
            "FkVDX0hFQURfSURfTU9ESUZZX0NPT0wQxgoSGwoWRUNfSEVBRF9JRF9NT0RJ",
            "RllfU0FNRRDHChIeChlFQ19IRUFEX0lEX01PRElGWV9JTlZBTElEEMgKEhYK",
            "EUVDX0VRVUlQX05PVEZPVU5EEPkKEh0KGEVDX0VRVUlQX1BPU19VTlFVQUxJ",
            "RklFRBD6ChIdChhFQ19FUVVJUF9TRVhfVU5RVUFMSUZJRUQQ+woSHQoYRUNf",
            "RVFVSVBfUFJPX1VOUVVBTElGSUVEEPwKEhcKEkVDX0VRVUlQX01BWF9MRVZF",
            "TBD9ChIgChtFQ19FUVVJUF9QTEFZRVJfTEVWRUxfTElNSVQQ/goSHAoXRUNf",
            "RVFVSVBfREVDT01QT1NFX05PTkUQ/woSHAoXRUNfRVFVSVBfQ0FOVF9ERUNP",
            "TVBPU0UQgAsSHwoaRUNfQ1VSUkVOQ1lfT1VUT0ZfQkFOS0NBUkQQ3QsSHgoZ",
            "RUNfQ1VSUkVOQ1lfT1VUT0ZfRElBTU9ORBDeCxIdChhFQ19DVVJSRU5DWV9P",
            "VVRPRl9TSUxWRVIQ3wsSIQocRUNfQ1VSUkVOQ1lfT1VUT0ZfQUlORkxVRU5D",
            "RRDgCxIcChdFQ19DVVJSRU5DWV9PVVRPRl9BRlVORBDhCxIkCh9FQ19DVVJS",
            "RU5DWV9PVVRPRl9BQ09OVFJJQlVUSU9OEOILEhwKF0VDX0NVUlJFTkNZX09V",
            "VE9GX0RGSVNIEOMLEiMKHkVDX0NVUlJFTkNZX09VVE9GX0NIRUVTRV9ERklT",
            "SBDkCxIfChpFQ19DVVJSRU5DWV9PVVRPRl9TVEFSTFVDSxDlCxIiCh1FQ19D",
            "VVJSRU5DWV9PVVRPRl9TT0xJQ0lUQ0FSRBDmCxIjCh5FQ19DVVJSRU5DWV9P",
            "VVRPRl9TRUxFQ1RUSUNLRVQQ5wsSHQoYRUNfQ1VSUkVOQ1lfT1VUT0ZfRkVU",
            "VEVSEOgLEh0KGEVDX0NVUlJFTkNZX09VVE9GX0NSRURJVBDpCxIfChpFQ19D",
            "VVJSRU5DWV9PVVRPRl9SQUJPVFRMRRDqCxIcChdFQ19DVVJSRU5DWV9PVVRP",
            "Rl9TVU5OWRDrCxIjCh5FQ19DVVJSRU5DWV9PVVRPRl9HUk9XX0ZFQVRIRVIQ",
            "7AsSIQocRUNfQ1VSUkVOQ1lfT1VUT0ZfQk9YX09GRklDRRDtCxIhChxFQ19D",
            "VVJSRU5DWV9PVVRPRl9HUkVFTl9MRUFGEO4LEiMKHkVDX0NVUlJFTkNZX09V",
            "VE9GX1dPUktTX0JBTExPVBDvCxInCiJFQ19DVVJSRU5DWV9PVVRPRl9FTkNP",
            "VU5URVJfVElDS0VUEPALEh4KGUVDX1BMT1RWSUVXX0NBTk5PVF9GSU5JU0gQ",
            "wQwSHwoaRUNfUExPVFZJRVdfQUxSRUFEWV9GSU5JU0gQwgwSGgoVRUNfUExP",
            "VFZJRVdfTkVFRF9QUkVWEMMMEhwKF0VDX1BMT1RWSUVXX05FRURfU0lMVkVS",
            "EMQMEiEKHEVDX1BMT1RWSUVXX05FRURfRklOSVNIX1RBU0sQxQwSIwoeRUNf",
            "TUFJTl9TVEFHRV9DQU5OT1RfQ0hBTExBTkdFEKUNEiMKHkVDX01BSU5fU1RB",
            "R0VfTkVFRF9GSU5JU0hfVEFTSxCmDRIiCh1FQ19NQUlOX1NUQUdFX05FRURf",
            "UFJFVl9TVEFHRRCnDRIXChJFQ19NQUlOX1NUQUdFX0xBU1QQqA0SFwoSRUNf",
            "R1VJTERfTkFNRV9VU0VEEIgOEhIKDUVDX0dVSUxEX0ZVTEwQiQ4SHQoYRUNf",
            "R1VJTERfRlVORF9USU1FU19MSU1UEIoOEhcKEkVDX0dVSUxEX09XTl9HVUlM",
            "RBCLDhIYChNFQ19HVUlMRF9OVUxMX0dVSUxEEIwOEhwKF0VDX0dVSUxEX0pP",
            "SU5fQ09PTF9ET1dOEI0OEiAKG0VDX0dVSUxEX1JFUEVBVF9BUFBMWV9HVUlM",
            "RBCODhIXChJFQ19HVUlMRF9BVVRIT1JJVFkQjw4SIwoeRUNfR1VJTERfQ0hB",
            "TExFTkdFX1RJTUVTX0xJTUlUEJAOEhoKFUVDX0dVSUxEX1NUQUdFX0ZJTklT",
            "SBCRDhIXChJFQ19HVUlMRF9OT1RfQVBQTFkQkg4SGQoURUNfR1VJTERfTEVW",
            "RUxfTElNSVQQkw4SHgoZRUNfR1VJTERfTUlBTF9USU1FU19MSU1JVBCUDhIf",
            "ChpFQ19HVUlMRF9UUkFJTl9MRVZFTF9MSU1JVBCVDhIlCiBFQ19HVUlMRF9T",
            "RUNSRVRBUklBVF9MRVZFTF9MSU1JVBCWDhIeChlFQ19HVUlMRF9CVUlMRF9U",
            "SU1FX0xJTUlUEJcOEh0KGEVDX0dVSUxEX1NLSUxMX01BWF9MRVZFTBCYDhIc",
            "ChdFQ19HVUlMRF9UUkFJTl9OT1RfT1BFThCZDhIgChtFQ19HVUlMRF9UUkFJ",
            "Tl9BTFJFQURZX09QRU4Qmg4SIAobRUNfR1VJTERfVEVBX1BBUlRZX05PVF9P",
            "UEVOEJsOEiQKH0VDX0dVSUxEX1RFQV9QQVJUWV9BTFJFQURZX09QRU4QnA4S",
            "KAojRUNfR1VJTERfVEVBX1BBUlRZX09QRU5fVElNRVNfTElNSVQQnQ4SIAob",
            "RUNfR1VJTERfQlVJTERJTkdfVVBHUkFESU5HEJ4OEh4KGUVDX0lETEVfUExB",
            "WV9TWVNfTk9UX09QRU4Q7A4SIAobRUNfSURMRV9QTEFZX0FERF9USU1FX0VN",
            "UFRZEO0OEhkKFEVDX0lETEVfUExBWV9OT1RISU5HEO4OEh4KGUVDX0lETEVf",
            "UExBWV9OT19NQUlOU1RBR0UQ7w4SGQoURUNfQVZXT1JLU19OT1RfRVhJU1QQ",
            "ng8SHAoXRUNfQVZXT1JLU19JTlZBTElEX05BTUUQnw8SHQoYRUNfQVZXT1JL",
            "U19GVUxMX1BPU0lUSU9OEKAPEhwKF0VDX0FWV09SS1NfRVZFTlRfVU5PUEVO",
            "EKEPEiIKHUVDX0FWV09SS1NfRVZFTlRfQUxSRUFEWV9ET05FEKIPEh8KGkVD",
            "X0FWV09SS1NfRVZFTlRfT1BUX0VSUk9SEKMPEhsKFkVDX0FWV09SS1NfU1RB",
            "R0VfRVJST1IQpA8SIgodRUNfQVZXT1JLU19GQU5TR0lGVF9OT1RfRVhJU1QQ",
            "pQ8SHwoaRUNfQVZXT1JLU19FWFRfUE9TX05PVF9GSVQQpg8SHAoXRUNfQVZX",
            "T1JLU19ST0xFX05PVF9GSVQQpw8SHQoYRUNfQVZXT1JLU19TUEVFRF9VUF9G",
            "VUxMEKgPEhwKF0VDX0FWV09SS1NfRVZFTlRfVU5ET05FEKkPEh8KGkVDX0FW",
            "V09SS1NfUFJPR1JFU1NfVU5GVUxMEKoPEh8KGkVDX0FWV09SS1NfVEVNUF9B",
            "VFRSX0VYSVNUEKsPEiAKG0VDX0FWV09SS1NfTkFNRV9OT1RfSElUX0tFWRCs",
            "DxIfChpFQ19BVldPUktTX1JPTEVfTk9UX0VOT1VHSBCtDxIfChpFQ19BVldP",
            "UktTX0xFTkdUSF9PVkVSRkxPVxCvDxInCiJFQ19BVldPUktTX0RJU0NVU1Nf",
            "REVHUkVFX09WRVJGTE9XELAPEh0KGEVDX0FWV09SS1NfU1RBUkxFVkVMX01B",
            "WBCxDxIdChhFQ19BVldPUktTX0RFQlJJU19SRVBFQVQQsg8SIAobRUNfQVZX",
            "T1JLU19ERUJSSVNfTk9URU5PVUdIELMPEh4KGUVDX0FWV09SS1NfREVCUklT",
            "X0lOVkFMSUQQtA8SKAojRUNfQVZXT1JLU19ESVNDVVNTX0RFR1JFRV9OT1RF",
            "Tk9VR0gQtQ8SJAofRUNfQVZXT1JLU19TVEFSTEVWRUxfTk9UX0VOT1VHSBC2",
            "DxIjCh5FQ19BVldPUktTX1NIT09UX0ZVTExfUE9TSVRJT04Qtw8SJQogRUNf",
            "QVZXT1JLU19SRVNIT09UX0ZVTExfUE9TSVRJT04QuA8SFQoQRUNfQVZXT1JL",
            "U19FWElTVBC5DxIpCiRFQ19BVldPUktTX0FUVFJfTkVFRF9TVEFSX05PVF9F",
            "Tk9VR0gQug8SGgoVRUNfUEFSVE5FUl9ET05UX0VYSVNUENAPEh0KGEVDX1BB",
            "UlRORVJfU0VORF9HSUZUX01BWBDRDxIhChxFQ19QQVJUTkVSX0FMTF9TRU5E",
            "X0dJRlRfTUFYENIPEiAKG0VDX1BBUlRORVJfRVZFTlRfRE9OVF9FWElTVBDT",
            "DxIdChhFQ19QQVJUTkVSX0VWRU5UX0lOVkFMSUQQ1A8SIQocRUNfUEFSVE5F",
            "Ul9JTlRFUkFDVF9OT19USU1FUxDVDxIjCh5FQ19QQVJUTkVSX1BIT1RPX0FM",
            "UkVBRFlfQlVZRUQQ1g8SGwoWRUNfUExPVF9BTFJFQURZX1BMQVlFRBC0EBIW",
            "ChFFQ19TSE9QX0lURU1fTEFDSxCYERIbChZFQ19TSE9QX0xJTUlUX0JZX0xF",
            "VkVMEJkREhsKFkVDX1NIT1BfVElNRV9OT1RfVkFMSUQQmhESIQocRUNfU0hP",
            "UF9MSU1JVF9CWV9HVUlMRF9MRVZFTBCbERIiCh1FQ19TSE9QX1JFRlJFU0hf",
            "VElNRVNfTElNSVRFRBCcERIeChlFQ19TSE9QX0lURU1fTElNSVRfQllfU0VY",
            "EJ0REiMKHkVDX1NIT1BfTElNSVRfQllfSElTVE9SWV9HUkFERRCeERISCg1F",
            "Q19QSE9ORV9IT0xEEPwREhoKFUVDX1BIT05FX1RPUElDX0ZJTklTSBD9ERIc",
            "ChdFQ19QSE9ORV9UT1BJQ19OT19SRUFEWRD+ERIiCh1FQ19QSE9ORV9UT1BJ",
            "Q19PUFRJT05fSUxMRUdBTBCAEhIdChhFQ19QSE9ORV9UT1BJQ19OT19SRVdB",
            "UkQQgRISEgoNRUNfV0VJQk9fSE9MRBDgEhIXChJFQ19XRUlCT19OT1RfRVhJ",
            "U1QQ4RISHQoYRUNfV0VJQk9fQUxSRUFEWV9GT1JXQVJEEOISEh0KGEVDX1dF",
            "SUJPX0FMUkVBRFlfQ09NTUVOVBDjEhIaChVFQ19XRUlCT19OT19OUENfV0VJ",
            "Qk8Q5BISGQoURUNfV0VJQk9fQ0FOTk9UX1BPU1QQ5RISEgoNRUNfR1JBREVf",
            "SE9MRBDEExIfChpFQ19HUkFERV9OT1RfUkVHSVNURVJfSU5GTxDFExIaChVF",
            "Q19HUkFERV9OT1RfQllfU1RBR0UQxhMSGAoTRUNfR1JBREVfTk9UX1RBUkdF",
            "VBDHExIXChJFQ19HUkFERV9SQU5LX1NQQU4QyBMSHAoXRUNfR1JBREVfQUxS",
            "RUFEWV9SRVdBUkQQyRMSFgoRRUNfR1JBREVfTk9fQVJFTkEQyhMSHAoXRUNf",
            "R1JBREVfTk9fUkVHSVNURVJJTkcQyxMSHAoXRUNfR1JBREVfUkVHU0lURVJf",
            "TElNSVQQzBMSHgoZRUNfR1JBREVfQUxSRUFEWV9SRUdTSVRFUhDNExIYChNF",
            "Q19HUkFERV9OVUxMX0dSQURFEM4TEiIKHUVDX0dSQURFX1JFR0lTVEVSX0NB",
            "TlRfQ0FOQ0VMEM8TEiQKH0VDX0dSQURFX0FMUkVBRFlfQUNISUVWRV9SRVdB",
            "UkQQ0BMSGQoURUNfR1JBREVfTk9fSU5fR1JBREUQ0RMSHQoYRUNfR1JBREVf",
            "REFUQV9FWFBJUkFUSU9OENITEhsKFkVDX0dSQURFX05FRURfUkVHSVNURVIQ",
            "0xMSFwoSRUNfR1JBREVfTkVFRF9UQVNLENQTEh8KGkVDX0dSQURFX0FTU0lT",
            "VF9OT1RfRU5PVUdIENUTEiAKG0VDX0dSQURFX09QUE9ORU5UX05PVF9GT1VO",
            "RBDWExIaChVFQ19HUkFERV9UUkFJTl9IQU5ETEUQ1xMSHAoXRUNfR1JBREVf",
            "SU5URVJWSUVXX1BSRVYQ2BMSHgoZRUNfR1JBREVfSU5URVJWSUVXX0ZJTklT",
            "SBDZExIRCgxFQ19DSEFUX0hPTEQQqBQSFgoRRUNfQ0hBVF9DRF9GUkVFWkUQ",
            "qRQSEwoORUNfQ0hBVF9CQU5ORUQQqhQSHAoXRUNfQ0hBVF9TWVNURU1fTk9U",
            "X09QRU4QqxQSEAoLRUNfU1dFRVBfQ0QQ2hQSEQoMRUNfUkFOS19IT0xEEIwV",
            "EhUKEEVDX0FDVElWSVRZX0hPTEQQ8BUSHAoXRUNfTUlETklHSFRfUExBWUJB",
            "Ul9GRUQQ8RUSIQocRUNfTUlETklHSFRfUExBWUJBUl9OT1RfRkVFRBDyFRId",
            "ChhFQ19NSUROSUdIVF9QTEFZQkFSX1dBSVQQ8xUSJQogRUNfTUlETklHSFRf",
            "UExBWUJBUl9CT05EQUdFX0ZVTEwQ9BUSKQokRUNfTUlETklHSFRfUExBWUJB",
            "Ul9NSU5DT05TVU1FX1RJTUVTEPUVEikKJEVDX01JRE5JR0hUX1BMQVlCQVJf",
            "TUlOQk9OREFHRV9MRVZFTBD2FRIZChRFQ19UT1VDSENBVF9OT1RfT1BFThCF",
            "FhIRCgxFQ19GQU5TX0hPTEQQ1BYSIQocRUNfRkFOU19SRVBFQVRfU0lHTl9D",
            "T05UUkFDVBDVFhIkCh9FQ19GQU5TX0NMVUJBQ1RJVklUWV9OT1RfTEVBREVS",
            "ENYWEigKI0VDX0ZBTlNfQ0xVQkFDVElWSVRZX0NBTk5PVF9BUlJBTkdFENcW",
            "EiQKH0VDX0ZBTlNfQ0xVQkFDVElWSVRZX05PVF9GSU5JU0gQ2BYSIAobRUNf",
            "RkFOU19SRUZSRVNIX1RJTUVTX0xJTUlUENkWEhkKFEVDX0ZBTlNfQ0FOTk9U",
            "X1JFU0VUENoWEhkKFEVDX0ZBTlNfRkNfTlVNX0VNUFRZENsWEiAKG0VDX0ZB",
            "TlNfQ0xVQkFDVElWSVRZX0ZJTklTSBDcFhIjCh5FQ19GQU5TX0NMVUJBQ1RJ",
            "VklUWV9OT1RfRVhJU1QQ3RYSKAojRUNfRkFOU19DTFVCQUNUSVZJVFlfQ0FO",
            "Tk9UX1NQRUVEVVAQ3hYSJAofRUNfRkFOU19DTFVCQUNUSVZJVFlfQUxMX0ZJ",
            "TklTSBDfFhImCiFFQ19GQU5TX0NMVUJBQ1RJVklUWV9JTlZJVEVfTElNSVQQ",
            "4BYSJQogRUNfRkFOU19DTFVCQUNUSVZJVFlfTk9UX1JFRlJFU0gQ4RYSKQok",
            "RUNfRkFOU19DTFVCQUNUSVZJVFlfT1ZFUl9CTEFDS1JBVElPEOIWEisKJkVD",
            "X0ZBTlNfQ0xVQkFDVElWSVRZX05PX1NQRUVEVVBfVElDS0VUEOMWEisKJkVD",
            "X0ZBTlNfQ0xVQkFDVElWSVRZX05PX1JFRlJFU0hfVElDS0VUEOQWEiQKH0VD",
            "X0ZBTlNfU0tJTExfVVBHUkFERV9OVU1fTElNSVQQ5RYSKgolRUNfRkFOU19T",
            "S0lMTF9VUEdSQURFX01BVEVSSUFMU19MSU1JVBDmFhImCiFFQ19GQU5TX1NL",
            "SUxMX1VQR1JBREVfTEVWRUxfTElNSVQQ5xYSKAojRUNfRkFOU19DTFVCQUNU",
            "SVZJVFlfQ09PTERPV05fTElNSVQQ6BYSHgoZRUNfRkFOU19CRU5FRklUX01B",
            "WF9USU1FUxDpFhIdChhFQ19GQU5TX0JFTkVGSVRfTk9UX09QRU4Q6hYSKwom",
            "RUNfRkFOU19DTFVCQUNUSVZJVFlfTk9UX0VOT1VHSF9USUNLRVQQ6xYSGwoW",
            "RUNfVEFTS19DQU5OT1RfUkVDSUVWRRC4FxIbChZFQ19UQVNLX0RBSUxZX0xJ",
            "VkVORVNTELkXEh4KGUVDX1NXRUVQX1RJTUVTX05PVF9FTk9VR0gQuhcSGQoU",
            "RUNfUkVDUlVJVF9GUkVFX05PTkUQnBgSFwoSRUNfUkVDUlVJVF9GUkVFX0NE",
            "EJ0YEiUKIEVDX1JFQ1JVSVRfRFJBV19USU1FU19OT1RfRU5PVUdIEJ4YEh0K",
            "GEVDX1JFQ1JVSVRfVFlQRV9OT1RfT1BFThCfGBIdChhFQ19SRUNSVUlUX1RZ",
            "UEVfTk9URk9VTkQQoBgSGQoURUNfQ09VUlNFX05PVF9UQUtJTkcQzhgSFQoQ",
            "RUNfQ09VUlNFX1RBS0lORxDPGBIdChhFQ19DT1VSU0VfTk9UX1NFTEVDVEFC",
            "TEUQ0BgSGAoTRUNfQ09VUlNFX05PX0xFU1NPThDRGBIdChhFQ19DT1VSU0Vf",
            "Tk9fUkVTVF9SRVdBUkQQ0hgSHwoaRUNfQ09VUlNFX1RPREFZX1NFTEVDVF9N",
            "QVgQ0xgSHgoZRUNfQ09VUlNFX1RJTUVTX05PVEVOT1VHSBDUGBIpCiRFQ19D",
            "T1VSU0VfQ0FOVF9VUEdSQURFX1RBS0lOR19DT1VSU0UQ1RgSGwoWRUNfQ09V",
            "UlNFX09QVElPTl9FUlJPUhDWGBIfChpFQ19DT1VSU0VfQ09VUlNFX01BWF9M",
            "SU1JVBDXGBIqCiVFQ19DT1VSU0VfQ09VUlNFX1JFV0FSRF9OT1RfQVZBSUxB",
            "QkxFENgYEiEKHEVDX0NPVVJTRV9DT1VSU0VfU0hFRVRfRVhJU1QQ2RgSJAof",
            "RUNfQ09VUlNFX0NPVVJTRV9UQUtFX0xFU1NPTl9DRBDaGBIcChdFQ19UT1dF",
            "Ul9FVkVOVF9IQU5ETElORxCAGRIbChZFQ19UT1dFUl9FVkVOVF9OT1NUQUdF",
            "EIEZEiAKG0VDX1RPV0VSX0VWRU5UX05PTElUVExFR0FNRRCCGRIZChRFQ19U",
            "T1dFUl9FVkVOVF9OT0xPVBCDGRIYChNFQ19UT1dFUl9OT1RfRklOSVNIEIQZ",
            "Eh8KGkVDX1RPV0VSX1JFU0VUX1RJTUVTX0xJTUlUEIUZEh8KGkVDX1RPV0VS",
            "X1NXRUVQX1RJTUVTX0xJTUlUEIYZEiEKHEVDX1RPV0VSX1NXRUVQX1JFUVVJ",
            "UkVfQkVHSU4QhxkSGQoURUNfVE9XRVJfU1dFRVBfTElNSVQQiBkSGgoVRUNf",
            "VE9XRVJfU0hPUF9QUk9EVUNUEIkZEhYKEUVDX1RPV0VSX05PVF9ORVhUEIoZ",
            "EhgKE0VDX1RPV0VSX1JPTEVfQ09VTlQQixkSFgoRRUNfUExBQ0VfTk9UX09Q",
            "RU4Q5RkSGQoURUNfUExBQ0VfVU5MT0NLX0ZVTEwQ5hkSIwoeRUNfUExBQ0Vf",
            "RklOSVNIX0pPQl9OT1RfRklOSVNIEOcZEiAKG0VDX1BMQUNFX1NQRUVEVVBf",
            "Tk9UV09SS0lORxDoGRIgChtFQ19QTEFDRV9TUEVFRFVQX0pPQl9GSU5JU0gQ",
            "6RkSIQocRUNfUExBQ0VfQVJSQU5HRV9KT0JfV09SS0lORxDqGRIeChlFQ19Q",
            "TEFDRV9BUlJBTkdFX05PVF9QQVNTEOsZEiAKG0VDX1BMQUNFX0FSUkFOR0Vf",
            "UVVFVUVfRlVMTBDsGRIiCh1FQ19QTEFDRV9BUlJBTkdFX1JPTEVfSU5WQUxJ",
            "RBDtGRIhChxFQ19QTEFDRV9BUlJBTkdFX1JPTEVfUkVQRUFUEO4ZEiMKHkVD",
            "X1BMQUNFX0FSUkFOR0VfUk9MRV9DT05GTElDVBDvGRIjCh5FQ19QTEFDRV9B",
            "UlJBTkdFX1JPTEVfTk9URVhJU1QQ8BkSJAofRUNfUExBQ0VfQ0hBTExFTkdF",
            "X0FMUkVBRFlfUEFTUxDxGRIhChxFQ19QTEFDRV9VUEdSQURFX0pPQl9XT1JL",
            "SU5HEPIZEiYKIUVDX1BMQUNFX1VQR1JBREVfTEVWRUxfTk9UX0VOT1VHSBDz",
            "GRImCiFFQ19QTEFDRV9VUEdSQURFX1RJTUVTX05PVF9FTk9VR0gQ9BkSHgoZ",
            "RUNfUExBQ0VfVVBHUkFERV9OT1RfUEFTUxD1GRIdChhFQ19QTEFDRV9TUEVF",
            "RFVQX0pPQl9NQVgQ9hkSGgoVRUNfRlNIT1dfTk9UX0FVRElUSU9OEMkaEhoK",
            "FUVDX0ZTSE9XX05PVF9LTk9DS09VVBDKGhIXChJFQ19GU0hPV19OT1RfRklO",
            "QUwQyxoSGgoVRUNfRlNIT1dfTk9UX1FVTElGSUVEEMwaEhMKDkVDX0ZTSE9X",
            "X1ZPVEVEEM0aEh4KGUVDX0ZTSE9XX09QRVJfTk9UX1NVUFBPUlQQzhoSHQoY",
            "RUNfRlNIT1dfRlJFRV9HSUZUX0xJTUlUEM8aEhsKFkVDX0ZTSE9XX0lOU1BJ",
            "UkVfTElNSVQQ0BoSFgoRRUNfRlNIT1dfTk9UX1ZPVEUQ0RoSFgoRRUNfRlNI",
            "T1dfUkVXQVJERUQQ0hoSGwoWRUNfRlNIT1dfQ0FOVF9SRVdBUkRFRBDTGhIb",
            "ChZFQ19GU0hPV19GQUNUSU9OX0xJTUlUENQaEhUKEEVDX0ZTSE9XX0NBUFRB",
            "SU4Q1RoSGAoTRUNfRlNIT1dfTk9fQ0FQVEFJThDWGhIbChZFQ19GU0hPV19O",
            "T1RfSk9JTl9URUFNENcaEh8KGkVDX0ZTSE9XX0FMUkVBRFlfSk9JTl9URUFN",
            "ENgaEhsKFkVDX0ZTSE9XX05PVF9DSEFMTEVOR0UQ2RoSHQoYRUNfRlNIT1df",
            "QUxSRUFEWV9BRFZJU09SENoaEhoKFUZDX0ZTSE9XX1JFVklWRV9MSU1JVBDb",
            "GhIZChRGQ19GU0hPV19SRVZJVkVfTU9SRRDcGhIXChJFQ19GU0hPV19OT1Rf",
            "QUZURVIQ3RoSHQoYRUNfRlNIT1dfTk9UX0JBTkRfTUVNQkVSEN4aEhgKE0VD",
            "X0ZTSE9XX1ZPVEVfTElNSVQQ3xoSHAoXRUNfRlNIT1dfTElWRU5FU1NfTElN",
            "SVQQ4BoSFwoSRUNfRlNIT1dfVEVBTV9GVUxMEOEaEhcKEkVDX0ZTSE9XX05P",
            "X0JBVFRMRRDiGhIaChVFQ19GU0hPV19SRVBFQVRfTUFUQ0gQ4xoSHAoXRUNf",
            "RlNIT1dfQURWSVNPUl9QSUNLRUQQ5BoSHQoYRUNfRlNIT1dfQURWSVNPUl9O",
            "T1RfTk9XEOUaEhgKE0VDX0ZTSE9XX0REX0NIT09TRUQQ5hoSGQoURUNfRlNI",
            "T1dfR1JBREVfTElNSVQQ5xoSHQoYRUNfRlJJRU5EX1JFUEVBVEVEX0FQUExZ",
            "EK0bEhkKFEVDX0ZSSUVORF9BUFBMWV9TRUxGEK4bEh0KGEVDX0ZSSUVORF9O",
            "T1RfRlJJRU5EU0hJUBCvGxIdChhFQ19GUklFTkRfQUxSRUFEWV9GUklFTkQQ",
            "sBsSGAoTRUNfRlJJRU5EX05VTV9MSU1JVBCxGxIfChpFQ19UQVJHRVRfRlJJ",
            "RU5EX05VTV9MSU1JVBCyGxIaChVFQ19GQVNISU9OX0xPU0VfQ0xPVEgQtxsS",
            "HQoYRUNfRkFTSElPTl9DT01QTEVURV9GQUlMELgbEhsKFkVDX0ZBU0hJT05f",
            "SVRFTV9MT0NLRUQQuRsSHQoYRUNfRkFTSElPTl9DQU5fQlVZX0NMT1RIELob",
            "EhwKF0VDX0ZBU0hJT05fSEFTX0NPTVBMRVRFELsbEhgKE0VDX0ZBU0hJT05f",
            "U0VMRUNURUQQvBsSGAoTRUNfRkFTSElPTl9OT1RfUEFSVBC9GxIbChZFQ19G",
            "QVNISU9OX05PVF9GQVNISU9OEL4bEhgKE0VDX0FWV09SS19TSE9XX0xPQ0sQ",
            "wBsSHQoYRUNfQVZXT1JLX1NIT1dfTk9UX1NIT09UEMEbEhwKF0VDX0FWV09S",
            "S19TSE9XX05PVF9IQUxMEMIbEh0KGEVDX0FWV09SS19TSE9XX0hBTExfRlVM",
            "TBDDGxIfChpFQ19BVldPUktfU0hPV19FTkpPWV9MSU1JVBDEGxIcChdFQ19B",
            "VldPUktfU0hPV19TTkFDS19DRBDFGxImCiFFQ19BVldPUktfU0hPV19BRERT",
            "TkFDS19NVVNUT1dORVIQxhsSIwoeRUNfQVZXT1JLX1NIT1dfU05BQ0tfTlVN",
            "X0xJTUlUEMcbEiUKIEVDX0FWV09SS19TSE9XX0dFVFNOQUNLX05PVE9OV0VS",
            "EMgbEh4KGUVDX0FWV09SS19TSE9XX05PTkVfU05BQ0sQyRsSJQogRUNfQVZX",
            "T1JLX1NIT1dfU05BQ0tfVElNRVNfTElNSVQQyhsSGwoWRUNfQVZXT1JLX1NI",
            "T1dfTk9UX05QQxDLGxIlCiBFQ19BVldPUktfU0hPV19NRVNTQUdFX0xFTl9M",
            "SU1JVBDMGxIiCh1FQ19BVldPUktfU0hPV19OT1RfRU5KT1lfU0VMRhDNGxIg",
            "ChtFQ19BVldPUktfU0hPV19FTkpPWV9SRVBFQVQQzhsSHwoaRUNfQVZXT1JL",
            "X1NIT1dfTk9UX1NFVFdPUksQzxsSHAoXRUNfQVZXT1JLX1NIT1dfTk9UT1dO",
            "RVIQ0BsSKQokRUNfQVZXT1JLX1NIT1dfQ0hBTkdFX1NOQUNLX05PVF9FWElU",
            "ENEbEh8KGkVDX0FWV09SS19TSE9XX05PVF9QUkVTSE9XENIbEioKJUVDX0FW",
            "V09SS19TSE9XX05PVF9DSEFOR0VfRklSU1RfU05BQ0sQ0xsSGgoVRUNfQVZX",
            "T1JLX1NIT1dfVU5MT0NLENQbEhsKFkVDX0FWV09SS19TSE9XX09QRU5JTkcQ",
            "1RsSHgoZRUNfQVZXT1JLX1NIT1dfU0VURURfV09SSxDWGxIdChhFQ19BVldP",
            "UktfU0hPV19HT1RfU05BQ0sQ1xsSGQoURUNfQUNUSVZJVFlfTk9UX09QRU4Q",
            "2BsSFwoSRUNfVEVBTV9JU19JTl9URUFNEN4bEhUKEEVDX1RFQU1fTk9UX1RF",
            "QU0Q3xsSFwoSRUNfVEVBTV9OT1RfTEVBREVSEOAbEhgKE0VDX1RFQU1fTk9U",
            "X0lOX1RFQU0Q4RsSGAoTRUNfVEVBTV9MRVZFTF9MSU1JVBDiGxIRCgxFQ19U",
            "RUFNX0ZVTEwQ4xsSGQoURUNfVEVBTV9OT1RfSU5fQVBQTFkQ5BsSEgoNRUNf",
            "VEVBTV9LTklDSxDlGxIVChBFQ19URUFNX0JFX0tOSUNLEOYbEhYKEUVDX1RF",
            "QU1fQkVfTEVBREVSEOcbEhwKF0VDX1RFQU1fVFJBTlNGRVJfTEVBREVSEOgb",
            "EhEKDEVDX1RFQU1fUVVJVBDpGxIbChZFQ19URUFNX1RBUkdFVF9PRkZMSU5F",
            "EOobEh0KGEVDX1RFQU1fVFlQRV9MRVZFTF9MSU1JVBDrGxIfChpFQ19URUFN",
            "X05PVF9JTl9JTlZJVEVfTElTVBDsGxIVChBFQ19URUFNX0lTX0lOX0ZCEO0b",
            "EhYKEUVDX1RFQU1fUE9TVF9GVUxMEO4bEhoKFUVDX1RFQU1fUkVQRUFURURf",
            "Uk9MRRDvGxIZChRFQ19URUFNX0hBU19FTUJBVFRMRRDwGxIeChlFQ19URUFN",
            "X0xFQURFUl9OT1RfQ0hBTkdFEPEbEh4KGUVDX1RFQU1fTUVNQkVSX0NIQU5H",
            "RV9PTkUQ8hsSHwoaRUNfVEVBTV9NRU1CRVJfQ0hBTkdFX1NFTEYQ8xsSFgoR",
            "RUNfVEVBTV9OT1RfUkVBRFkQ9BsSFQoQRUNfVEVBTV9JU19SRUFEWRD1GxIZ",
            "ChRFQ19URUFNX0VNQkFUVExFX05VTRD2GxIYChNFQ19URUFNX05PVF9JTl9Q",
            "TEFZEPcbEhwKF0VDX1RFQU1fUExBWV9UWVBFX0VSUk9SEPgbEh4KGUVDX1RF",
            "QU1fUExBWV9SRVBMQUNFX1BBU1QQ+RsSHgoZRUNfVEVBTV9QTEFZX1JFV0FS",
            "RF9USU1FUxD6GxIdChhFQ19URUFNX1BMQVlfSVNfRklHSFRJTkcQ+xsSGwoW",
            "RUNfVEVBTV9UQVJHRVRfSU5fVEVBTRD8GxIYChNFQ19URUFNX0xBQ0tfTUVN",
            "QkVSEP0bEh8KGkVDX1RFQU1fSVNfV0FJVElOR19DT05GSVJNEP4bEhYKEUVD",
            "X1RFQU1fUkVMSUVWSU5HEP8bEh0KGEVDX1RFQU1fUkVMSUVWRV9BTlNXRVJF",
            "RBCAHBIcChdFQ19URUFNX1JFTElFVkVfVElNRU9VVBCBHBIfChpFQ19URUFN",
            "X1JFTElFVkVfTk9UX0pPSU5FUhCCHBIXChJFQ19URUFNX1JFTElFVkVfQ0QQ",
            "gxwSGQoURUNfVEVBTV9TUEVDSUFMX1BMQVkQhBwSIQocRUNfVEVBTV9DSEFO",
            "R0VfRU1CQVRUTEVfRkFJTBCFHBIfChpFQ19URUFNX1RFQU1QTEFZX1NPTE9f",
            "RkFJTBCGHBIcChdFQ19URUFNX1dPUkxEX0lOVklURV9DRBCHHBIbChZFQ19U",
            "RUFNX01FTUJFUl9IQU5HX1VQEIgcEhcKEkVDX1RFQU1fTk9fSEFOR19VUBCJ",
            "HBIYChNFQ19URUFNX0NBTExCQUNLX0NEEIocEhYKEUVDX1RFQU1fSk9JTl9G",
            "QUlMEIscEhoKFUVDX1RFQU1fUExBWV9OT1RfT1BFThCMHBIdChhFQ19URUFN",
            "X0hBTkdJTkdfTk9UX09QRU4QjRwSGQoURUNfV0FSX05PVF9DSEFMTEVOR0UQ",
            "kBwSFQoQRUNfV0FSX05PVF9FWElTVBCRHBIWChFFQ19XQVJfSEFTX0ZJTklT",
            "SBCSHBIWChFFQ19XQVJfU0tJTExfQ0FTVBCTHBIUCg9FQ19XQVJfTUlTU19R",
            "VEUQlBwSGgoVRUNfVFJBSU5UT09MX05PVF9DQVJEEKQcEh0KGEVDX1RSQUlO",
            "VE9PTF9MRVZFTF9MSU1JVBClHBIbChZFQ19UUkFJTlRPT0xfSVNfVU5MT0NL",
            "EKYcEhYKEUVDX1RSQUlOVE9PTF9MT0NLEKccEhYKEUVDX1RSQUlOVE9PTF9Q",
            "QVNTEKgcEh0KGEVDX1RSQUlOVE9PTF9DQU5UX0FTU0lTVBCpHBIcChdFQ19U",
            "UkFJTlRPT0xfUFJPRl9MSU1JVBCrHBIcChdFQ19UUkFJTlRPT0xfQ0FSRF9M",
            "SU1JVBCsHBIbChZFQ19UUkFJTlRPT0xfTlVNX0xJTUlUEK0cEiQKH0VDX1RS",
            "QUlOVE9PTF9BU1NJU1RfVElNRVNfTElNSVQQrhwSJQogRUNfVFJBSU5UT09M",
            "X0FTU0lTVF9GSVJFTkRfTElNSVQQrxwSHgoZRUNfVFJBSU5UT09MX0NIQUxM",
            "RU5HRV9DRBCwHBIiCh1FQ19UUkFJTlRPT0xfTk9fRlJJRU5EX0FTU0lTVBCx",
            "HBIZChRFQ19UUkFJTlRPT0xfTk9fUk9MRRCyHBIcChdFQ19UUkFJTlRPT0xf",
            "Tk9UX1BMQVlFUhCzHBIhChxFQ19GQVNISU9OX05PVF9VTkxPQ0tfU0NIRU1F",
            "EMIcEh8KGkVDX0ZBU0hJT05fSEFWRV9OT1RfU0NIRU1FEMMcEhsKFkVDX0ZB",
            "U0hJT05fUEFSVF9SRVBFQVQQxBwSHwoaRUNfRkFTSElPTl9VTkxPQ0tFRF9T",
            "Q0hFTUUQxRwSIQocRUNfRkFTSElPTl9VTkxPQ0tfQUxMX1NDSEVNRRDGHBIb",
            "ChZFQ19GQVNISU9OX05PVF9QQUNLQUdFEMccEhgKE0VDX0ZBU0hJT05fUkVX",
            "QVJERUQQyBwSIQocRUNfRkFTSElPTl9CUkFORF9MRVZFTF9MSU1JVBDJHBIg",
            "ChtFQ19GQVNISU9OX0JSQU5EX1NDT1JFX0xFU1MQyhwSHwoaRUNfRkFTSElP",
            "Tl9TRUxFQ1RfU0VYX0ZBSUwQyxwSHwoaRUNfRkFTSElPTl9TQ0hFTUVfTkFN",
            "RV9MRU4QzBwSGgoVRUNfRkFTSElPTl9OT1RfRU5PVUdIEM0cEh0KGEVDX0ZB",
            "U0hJT05fTk9UX01BS0VQQVBFUhDOHBIfChpFQ19GQVNISU9OX1NUQUdFX05P",
            "VF9TVEFHRRDgHBIgChtFQ19GQVNISU9OX1NUQUdFX1BMT1RfTElNSVQQ4RwS",
            "FQoQRUNfVElUTEVfQUNUSVZFRBD0HBISCg1FQ19USVRMRV9VU0VEEPUcEhgK",
            "E0VDX1RJVExFX05PVF9FTk9VR0gQ9hwSFwoSRUNfVElUTEVfTk9UX1RJVExF",
            "EPccEg0KCEVDX09USEVSEKAfYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Stardom.ErrorCode), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 错误码
  /// </summary>
  public enum ErrorCode {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("EC_SUCCESS")] EcSuccess = 0,
    /// <summary>
    /// 通用系统错误
    /// </summary>
    [pbr::OriginalName("EC_FAIL")] EcFail = 1,
    /// <summary>
    /// 发生了未知错误
    /// </summary>
    [pbr::OriginalName("EC_UNKNOWN")] EcUnknown = 2,
    /// <summary>
    /// 当前版本过低
    /// </summary>
    [pbr::OriginalName("EC_APP_VERSION")] EcAppVersion = 3,
    /// <summary>
    /// token有误
    /// </summary>
    [pbr::OriginalName("EC_TOKEN")] EcToken = 4,
    /// <summary>
    /// 新用户，没有玩家
    /// </summary>
    [pbr::OriginalName("EC_NOT_PLAYERS")] EcNotPlayers = 5,
    /// <summary>
    /// 参数错误
    /// </summary>
    [pbr::OriginalName("EC_PARAM_ERROR")] EcParamError = 6,
    /// <summary>
    /// 找不到配置
    /// </summary>
    [pbr::OriginalName("EC_CONFIG_NOTFOUND")] EcConfigNotfound = 7,
    /// <summary>
    /// 当前费用不足
    /// </summary>
    [pbr::OriginalName("EC_FEE_NOTENOUGH")] EcFeeNotenough = 8,
    /// <summary>
    /// 配置出错
    /// </summary>
    [pbr::OriginalName("EC_CONFIG_ERROR")] EcConfigError = 9,
    /// <summary>
    /// 唱跳RAP~
    /// </summary>
    [pbr::OriginalName("EC_NO_EXPORT_TIPS")] EcNoExportTips = 12,
    /// <summary>
    /// 本服尚未开放，请稍后再试
    /// </summary>
    [pbr::OriginalName("EC_NO_OPEN_TIME")] EcNoOpenTime = 13,
    /// <summary>
    /// 账号异处登录
    /// </summary>
    [pbr::OriginalName("EC_ACCOUNT_LOGIN_OTHER")] EcAccountLoginOther = 14,
    /// <summary>
    /// 账号不在白名单中
    /// </summary>
    [pbr::OriginalName("EC_NOT_IN_WHITE_LIST")] EcNotInWhiteList = 15,
    /// <summary>
    /// 本服已关闭注册
    /// </summary>
    [pbr::OriginalName("EC_CLOSE_REGISTER")] EcCloseRegister = 16,
    /// <summary>
    /// 空，无飘字
    /// </summary>
    [pbr::OriginalName("EC_EMPTY")] EcEmpty = 99,
    /// <summary>
    /// 没有阵营
    /// </summary>
    [pbr::OriginalName("EC_NO_FACTION")] EcNoFaction = 100,
    /// <summary>
    /// 非法词汇
    /// </summary>
    [pbr::OriginalName("EC_WORD_SENSITIVE")] EcWordSensitive = 101,
    /// <summary>
    /// 名称被使用
    /// </summary>
    [pbr::OriginalName("EC_NAME_BEEN_USED")] EcNameBeenUsed = 102,
    /// <summary>
    /// 没有协会
    /// </summary>
    [pbr::OriginalName("EC_NO_GUILD")] EcNoGuild = 103,
    /// <summary>
    /// 用户名字符超出指定长度
    /// </summary>
    [pbr::OriginalName("EC_NAME_TOO_LONG")] EcNameTooLong = 104,
    /// <summary>
    /// 挑战次数限制
    /// </summary>
    [pbr::OriginalName("EC_CHALLENGE_TIMES_LIMIT")] EcChallengeTimesLimit = 105,
    /// <summary>
    /// 次数限制
    /// </summary>
    [pbr::OriginalName("EC_TIMES_LIMIT")] EcTimesLimit = 106,
    /// <summary>
    /// 购买次数限制
    /// </summary>
    [pbr::OriginalName("EC_BUY_TIMES_LIMIT")] EcBuyTimesLimit = 107,
    /// <summary>
    /// 关卡已结束
    /// </summary>
    [pbr::OriginalName("EC_STAGE_FINISH")] EcStageFinish = 108,
    /// <summary>
    /// 关卡不存在
    /// </summary>
    [pbr::OriginalName("EC_STAGE_NOT_FOUND")] EcStageNotFound = 109,
    /// <summary>
    /// 等级限制
    /// </summary>
    [pbr::OriginalName("EC_LEVEL_LIMIT")] EcLevelLimit = 110,
    /// <summary>
    /// 物品不可用
    /// </summary>
    [pbr::OriginalName("EC_ILLEGAL_ITEM")] EcIllegalItem = 111,
    /// <summary>
    /// 协会影响力不足 
    /// </summary>
    [pbr::OriginalName("EC_GUILD_INFLUENCE")] EcGuildInfluence = 112,
    /// <summary>
    /// 内容太短 
    /// </summary>
    [pbr::OriginalName("EC_CONTENT_TOO_SHORT")] EcContentTooShort = 113,
    /// <summary>
    /// 内容太长
    /// </summary>
    [pbr::OriginalName("EC_CONTENT_TOO_LONG")] EcContentTooLong = 114,
    /// <summary>
    /// 奖励已领取
    /// </summary>
    [pbr::OriginalName("EC_ALREADY_REWARD")] EcAlreadyReward = 115,
    /// <summary>
    /// 非法词汇：{sensitive_word}
    /// </summary>
    [pbr::OriginalName("EC_WORD_SENSITIVE_DETAIL")] EcWordSensitiveDetail = 116,
    /// <summary>
    /// 请先完成任务
    /// </summary>
    [pbr::OriginalName("EC_NEED_FINISH_TASK")] EcNeedFinishTask = 117,
    /// <summary>
    /// 您的包裹已满，请先清理包裹
    /// </summary>
    [pbr::OriginalName("EC_BAG_FULL_ITEM")] EcBagFullItem = 118,
    /// <summary>
    /// 您的包裹已满，请在包裹的装备页签分解装备
    /// </summary>
    [pbr::OriginalName("EC_BAG_FULL_EQUIP")] EcBagFullEquip = 119,
    /// <summary>
    /// 您的包裹已满，请先清理包裹
    /// </summary>
    [pbr::OriginalName("EC_BAG_FULL_DEBRIS")] EcBagFullDebris = 120,
    /// <summary>
    /// 您的包裹已满，请先清理包裹
    /// </summary>
    [pbr::OriginalName("EC_BAG_FULL_ROLECARD")] EcBagFullRolecard = 121,
    /// <summary>
    /// 您的包裹已满，请先清理包裹
    /// </summary>
    [pbr::OriginalName("EC_BAG_FULL_AVWORKS")] EcBagFullAvworks = 122,
    /// <summary>
    /// 您的包裹已满，请先清理包裹
    /// </summary>
    [pbr::OriginalName("EC_BAG_FULL_FASHION")] EcBagFullFashion = 123,
    /// <summary>
    /// 挑战已取消
    /// </summary>
    [pbr::OriginalName("EC_WAR_CANCEL")] EcWarCancel = 124,
    /// <summary>
    /// 奖励已领取       
    /// </summary>
    [pbr::OriginalName("EC_REWARD_ALREADY")] EcRewardAlready = 125,
    /// <summary>
    /// 玩家已登录
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_REPEAT")] EcLoginRepeat = 200,
    /// <summary>
    /// 请先登录
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_NO_LOGIN")] EcLoginNoLogin = 202,
    /// <summary>
    /// 鉴权失败
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_VERIFY_FAIL")] EcLoginVerifyFail = 203,
    /// <summary>
    /// 已拥有玩家
    /// </summary>
    [pbr::OriginalName("EC_CREATE_OWN_PLAYER")] EcCreateOwnPlayer = 204,
    /// <summary>
    /// 创建角色失败
    /// </summary>
    [pbr::OriginalName("EC_CREATE_ID_NOTFOUND")] EcCreateIdNotfound = 205,
    /// <summary>
    /// 请使用特定ID登录
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_ACCOUNT_LIMIT")] EcLoginAccountLimit = 206,
    /// <summary>
    /// 本服人数到达上限，请稍后再试
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_ONLINE_LIMIT")] EcLoginOnlineLimit = 207,
    /// <summary>
    /// 本服限制注册
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_REGISTER_LIMIT")] EcLoginRegisterLimit = 208,
    /// <summary>
    /// 当前用户不存在
    /// </summary>
    [pbr::OriginalName("EC_PLAYER_NOTFOUND")] EcPlayerNotfound = 1001,
    /// <summary>
    /// 当前等级不足
    /// </summary>
    [pbr::OriginalName("EC_PLAYER_LEVEL")] EcPlayerLevel = 1002,
    /// <summary>
    /// 咖位限制
    /// </summary>
    [pbr::OriginalName("EC_PLAYER_KAWEI")] EcPlayerKawei = 1003,
    /// <summary>
    /// 粉丝数限制
    /// </summary>
    [pbr::OriginalName("EC_PLAYER_FANS")] EcPlayerFans = 1004,
    /// <summary>
    /// 该道具不存在
    /// </summary>
    [pbr::OriginalName("EC_PROP_NOTFOUND")] EcPropNotfound = 1103,
    /// <summary>
    /// 该道具数量不足
    /// </summary>
    [pbr::OriginalName("EC_PROP_NUM_NOTENOUGH")] EcPropNumNotenough = 1104,
    /// <summary>
    /// 该道具不可使用
    /// </summary>
    [pbr::OriginalName("EC_PROP_CANNOTUSE")] EcPropCannotuse = 1105,
    /// <summary>
    /// 该道具不可出售
    /// </summary>
    [pbr::OriginalName("EC_PROP_CANNOTSELL")] EcPropCannotsell = 1106,
    /// <summary>
    /// 该道具不符合要求
    /// </summary>
    [pbr::OriginalName("EC_PROP_STUFF_NOT_FIT")] EcPropStuffNotFit = 1107,
    /// <summary>
    /// 已经领取奖励
    /// </summary>
    [pbr::OriginalName("EC_ALREADY_REWARDED")] EcAlreadyRewarded = 1108,
    /// <summary>
    /// 背包空间已满
    /// </summary>
    [pbr::OriginalName("EC_BAG_FULL")] EcBagFull = 1109,
    /// <summary>
    /// {itemname}今日获得上限
    /// </summary>
    [pbr::OriginalName("EC_PROP_GAIN_LIMIT")] EcPropGainLimit = 1110,
    /// <summary>
    /// 道具使用到达上限
    /// </summary>
    [pbr::OriginalName("EC_PROP_USE_LIMIT")] EcPropUseLimit = 1111,
    /// <summary>
    /// 礼包码不存在
    /// </summary>
    [pbr::OriginalName("EC_GIFT_CODE_NOT_EXIST")] EcGiftCodeNotExist = 1112,
    /// <summary>
    /// 礼包码已使用
    /// </summary>
    [pbr::OriginalName("EC_GIFT_CODE_USED")] EcGiftCodeUsed = 1113,
    /// <summary>
    /// 礼包使用等级不符合
    /// </summary>
    [pbr::OriginalName("EC_PROP_USE_LEVEL_LIMIT")] EcPropUseLevelLimit = 1114,
    /// <summary>
    /// 宝石数量不足
    /// </summary>
    [pbr::OriginalName("EC_GEM_NOT_ENOUGH")] EcGemNotEnough = 1115,
    /// <summary>
    /// 该名角色不存在
    /// </summary>
    [pbr::OriginalName("EC_ROLE_NOTFOUND")] EcRoleNotfound = 1201,
    /// <summary>
    /// 该名角色等级不足
    /// </summary>
    [pbr::OriginalName("EC_ROLE_LEVEL_UNQUALIFIED")] EcRoleLevelUnqualified = 1202,
    /// <summary>
    /// 该名角色性别不符
    /// </summary>
    [pbr::OriginalName("EC_ROLE_SEX_UNQUALIFIED")] EcRoleSexUnqualified = 1203,
    /// <summary>
    /// 该名角色职业不符
    /// </summary>
    [pbr::OriginalName("EC_ROLE_PRO_UNQUALIFIED")] EcRoleProUnqualified = 1204,
    /// <summary>
    /// 该名角色已到最大等级
    /// </summary>
    [pbr::OriginalName("EC_ROLE_MAX_LEVEL")] EcRoleMaxLevel = 1205,
    /// <summary>
    /// 卡牌角色已存在
    /// </summary>
    [pbr::OriginalName("EC_ROLE_ROLE_ALREADY_EXIST")] EcRoleRoleAlreadyExist = 1206,
    /// <summary>
    /// 主角不允许升级
    /// </summary>
    [pbr::OriginalName("EC_ROLE_UP_PLAYER")] EcRoleUpPlayer = 1207,
    /// <summary>
    /// 已到达突破限制
    /// </summary>
    [pbr::OriginalName("EC_ROLE_NO_BREAK")] EcRoleNoBreak = 1208,
    /// <summary>
    /// 已到达进修限制
    /// </summary>
    [pbr::OriginalName("EC_ROLE_NO_AWAKEN")] EcRoleNoAwaken = 1209,
    /// <summary>
    /// 突破等级不足
    /// </summary>
    [pbr::OriginalName("EC_ROLE_NEED_BREAK")] EcRoleNeedBreak = 1210,
    /// <summary>
    /// 已到达品质限制
    /// </summary>
    [pbr::OriginalName("EC_ROLE_NEXT_QUALITY")] EcRoleNextQuality = 1211,
    /// <summary>
    /// 该名角色不需要重塑
    /// </summary>
    [pbr::OriginalName("EC_ROLE_REMODEL_INITIAL")] EcRoleRemodelInitial = 1212,
    /// <summary>
    /// 需先完成主线剧情
    /// </summary>
    [pbr::OriginalName("EC_ROLE_QUALITY_PLOT")] EcRoleQualityPlot = 1213,
    /// <summary>
    /// 需先完成挑战关卡
    /// </summary>
    [pbr::OriginalName("EC_ROLE_QUALITY_CHALLENGE")] EcRoleQualityChallenge = 1214,
    /// <summary>
    /// 需先缴纳道具
    /// </summary>
    [pbr::OriginalName("EC_ROLE_QUALITY_PROPS")] EcRoleQualityProps = 1215,
    /// <summary>
    /// 需要完成所有条件
    /// </summary>
    [pbr::OriginalName("EC_ROLE_QUALITY_NOT_FIT")] EcRoleQualityNotFit = 1216,
    /// <summary>
    /// 需要进阶才可以升级
    /// </summary>
    [pbr::OriginalName("EC_ROLE_ENERGIZE_LIMIT")] EcRoleEnergizeLimit = 1217,
    /// <summary>
    /// 赋能不足，无法进阶
    /// </summary>
    [pbr::OriginalName("EC_ROLE_ENERGIZE_NOT_ENOUGH")] EcRoleEnergizeNotEnough = 1218,
    /// <summary>
    /// 该位置已被占用 
    /// </summary>
    [pbr::OriginalName("EC_ROLE_POS_NOTALLOW")] EcRolePosNotallow = 1301,
    /// <summary>
    /// 该名角色已上阵
    /// </summary>
    [pbr::OriginalName("EC_ROLE_POS_ALREADY")] EcRolePosAlready = 1302,
    /// <summary>
    /// 修改角色头像冷却
    /// </summary>
    [pbr::OriginalName("EC_HEAD_ID_MODIFY_COOL")] EcHeadIdModifyCool = 1350,
    /// <summary>
    /// 角色头像相同
    /// </summary>
    [pbr::OriginalName("EC_HEAD_ID_MODIFY_SAME")] EcHeadIdModifySame = 1351,
    /// <summary>
    /// 改头像不可用
    /// </summary>
    [pbr::OriginalName("EC_HEAD_ID_MODIFY_INVALID")] EcHeadIdModifyInvalid = 1352,
    /// <summary>
    /// 该装备不存在
    /// </summary>
    [pbr::OriginalName("EC_EQUIP_NOTFOUND")] EcEquipNotfound = 1401,
    /// <summary>
    /// 装备位置错误
    /// </summary>
    [pbr::OriginalName("EC_EQUIP_POS_UNQUALIFIED")] EcEquipPosUnqualified = 1402,
    /// <summary>
    /// 该装备与当前角色性别不符
    /// </summary>
    [pbr::OriginalName("EC_EQUIP_SEX_UNQUALIFIED")] EcEquipSexUnqualified = 1403,
    /// <summary>
    /// 该装备与当前职业不符
    /// </summary>
    [pbr::OriginalName("EC_EQUIP_PRO_UNQUALIFIED")] EcEquipProUnqualified = 1404,
    /// <summary>
    /// 该装备已到强化最大等级
    /// </summary>
    [pbr::OriginalName("EC_EQUIP_MAX_LEVEL")] EcEquipMaxLevel = 1405,
    /// <summary>
    /// 主角等级限制
    /// </summary>
    [pbr::OriginalName("EC_EQUIP_PLAYER_LEVEL_LIMIT")] EcEquipPlayerLevelLimit = 1406,
    /// <summary>
    /// 分解装备数量不能为0
    /// </summary>
    [pbr::OriginalName("EC_EQUIP_DECOMPOSE_NONE")] EcEquipDecomposeNone = 1407,
    /// <summary>
    /// 该装备不能分解
    /// </summary>
    [pbr::OriginalName("EC_EQUIP_CANT_DECOMPOSE")] EcEquipCantDecompose = 1408,
    /// <summary>
    /// 银行卡余额不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_BANKCARD")] EcCurrencyOutofBankcard = 1501,
    /// <summary>
    /// 钻石不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_DIAMOND")] EcCurrencyOutofDiamond = 1502,
    /// <summary>
    /// 银币不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_SILVER")] EcCurrencyOutofSilver = 1503,
    /// <summary>
    /// 协会影响力不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_AINFLUENCE")] EcCurrencyOutofAinfluence = 1504,
    /// <summary>
    /// 协会资金不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_AFUND")] EcCurrencyOutofAfund = 1505,
    /// <summary>
    /// 协会贡献度不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_ACONTRIBUTION")] EcCurrencyOutofAcontribution = 1506,
    /// <summary>
    /// 小鱼干不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_DFISH")] EcCurrencyOutofDfish = 1507,
    /// <summary>
    /// 芝士鱼干不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_CHEESE_DFISH")] EcCurrencyOutofCheeseDfish = 1508,
    /// <summary>
    /// 星运点不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_STARLUCK")] EcCurrencyOutofStarluck = 1509,
    /// <summary>
    /// 招揽卡不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_SOLICITCARD")] EcCurrencyOutofSolicitcard = 1510,
    /// <summary>
    /// 选拔券不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_SELECTTICKET")] EcCurrencyOutofSelectticket = 1511,
    /// <summary>
    /// 羁绊点不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_FETTER")] EcCurrencyOutofFetter = 1512,
    /// <summary>
    /// 学分不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_CREDIT")] EcCurrencyOutofCredit = 1513,
    /// <summary>
    /// 试剂瓶不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_RABOTTLE")] EcCurrencyOutofRabottle = 1514,
    /// <summary>
    /// 心晴值不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_SUNNY")] EcCurrencyOutofSunny = 1515,
    /// <summary>
    /// 成长羽翼不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_GROW_FEATHER")] EcCurrencyOutofGrowFeather = 1516,
    /// <summary>
    /// 票房不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_BOX_OFFICE")] EcCurrencyOutofBoxOffice = 1517,
    /// <summary>
    /// 绿叶点数不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_GREEN_LEAF")] EcCurrencyOutofGreenLeaf = 1518,
    /// <summary>
    /// 作品竞投券不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_WORKS_BALLOT")] EcCurrencyOutofWorksBallot = 1519,
    /// <summary>
    /// 际遇刷新券不足
    /// </summary>
    [pbr::OriginalName("EC_CURRENCY_OUTOF_ENCOUNTER_TICKET")] EcCurrencyOutofEncounterTicket = 1520,
    /// <summary>
    /// 当前剧情不可完成
    /// </summary>
    [pbr::OriginalName("EC_PLOTVIEW_CANNOT_FINISH")] EcPlotviewCannotFinish = 1601,
    /// <summary>
    /// 剧情关卡已完成
    /// </summary>
    [pbr::OriginalName("EC_PLOTVIEW_ALREADY_FINISH")] EcPlotviewAlreadyFinish = 1602,
    /// <summary>
    /// 需先完成前置剧情
    /// </summary>
    [pbr::OriginalName("EC_PLOTVIEW_NEED_PREV")] EcPlotviewNeedPrev = 1603,
    /// <summary>
    /// 需使用金币解锁
    /// </summary>
    [pbr::OriginalName("EC_PLOTVIEW_NEED_SILVER")] EcPlotviewNeedSilver = 1604,
    /// <summary>
    /// 请先完成主线任务并领取任务奖励
    /// </summary>
    [pbr::OriginalName("EC_PLOTVIEW_NEED_FINISH_TASK")] EcPlotviewNeedFinishTask = 1605,
    /// <summary>
    /// 当前战斗关卡不可挑战
    /// </summary>
    [pbr::OriginalName("EC_MAIN_STAGE_CANNOT_CHALLANGE")] EcMainStageCannotChallange = 1701,
    /// <summary>
    /// 请先完成主线任务并领取任务奖励
    /// </summary>
    [pbr::OriginalName("EC_MAIN_STAGE_NEED_FINISH_TASK")] EcMainStageNeedFinishTask = 1702,
    /// <summary>
    /// 请先完成前置关卡
    /// </summary>
    [pbr::OriginalName("EC_MAIN_STAGE_NEED_PREV_STAGE")] EcMainStageNeedPrevStage = 1703,
    /// <summary>
    /// 最后一关
    /// </summary>
    [pbr::OriginalName("EC_MAIN_STAGE_LAST")] EcMainStageLast = 1704,
    /// <summary>
    /// 协会名称已被占用
    /// </summary>
    [pbr::OriginalName("EC_GUILD_NAME_USED")] EcGuildNameUsed = 1800,
    /// <summary>
    /// 该协会已满员
    /// </summary>
    [pbr::OriginalName("EC_GUILD_FULL")] EcGuildFull = 1801,
    /// <summary>
    /// 缴纳资金次数达到上限
    /// </summary>
    [pbr::OriginalName("EC_GUILD_FUND_TIMES_LIMT")] EcGuildFundTimesLimt = 1802,
    /// <summary>
    /// 已拥有协会
    /// </summary>
    [pbr::OriginalName("EC_GUILD_OWN_GUILD")] EcGuildOwnGuild = 1803,
    /// <summary>
    /// 协会不存在
    /// </summary>
    [pbr::OriginalName("EC_GUILD_NULL_GUILD")] EcGuildNullGuild = 1804,
    /// <summary>
    /// 加入协会时间冷却中（剩余{0}秒）
    /// </summary>
    [pbr::OriginalName("EC_GUILD_JOIN_COOL_DOWN")] EcGuildJoinCoolDown = 1805,
    /// <summary>
    /// 重复申请协会
    /// </summary>
    [pbr::OriginalName("EC_GUILD_REPEAT_APPLY_GUILD")] EcGuildRepeatApplyGuild = 1806,
    /// <summary>
    /// 没有协会权限
    /// </summary>
    [pbr::OriginalName("EC_GUILD_AUTHORITY")] EcGuildAuthority = 1807,
    /// <summary>
    /// 挑战次数限制
    /// </summary>
    [pbr::OriginalName("EC_GUILD_CHALLENGE_TIMES_LIMIT")] EcGuildChallengeTimesLimit = 1808,
    /// <summary>
    /// 协会关卡已结束
    /// </summary>
    [pbr::OriginalName("EC_GUILD_STAGE_FINISH")] EcGuildStageFinish = 1809,
    /// <summary>
    /// 没有申请协会
    /// </summary>
    [pbr::OriginalName("EC_GUILD_NOT_APPLY")] EcGuildNotApply = 1810,
    /// <summary>
    /// 协会等级限制
    /// </summary>
    [pbr::OriginalName("EC_GUILD_LEVEL_LIMIT")] EcGuildLevelLimit = 1811,
    /// <summary>
    /// 今天没次数了
    /// </summary>
    [pbr::OriginalName("EC_GUILD_MIAL_TIMES_LIMIT")] EcGuildMialTimesLimit = 1812,
    /// <summary>
    /// 协会培训部等级不足
    /// </summary>
    [pbr::OriginalName("EC_GUILD_TRAIN_LEVEL_LIMIT")] EcGuildTrainLevelLimit = 1813,
    /// <summary>
    /// 协会秘书部等级不足
    /// </summary>
    [pbr::OriginalName("EC_GUILD_SECRETARIAT_LEVEL_LIMIT")] EcGuildSecretariatLevelLimit = 1814,
    /// <summary>
    /// 协会建立时间不足
    /// </summary>
    [pbr::OriginalName("EC_GUILD_BUILD_TIME_LIMIT")] EcGuildBuildTimeLimit = 1815,
    /// <summary>
    /// 协会技能已经满级
    /// </summary>
    [pbr::OriginalName("EC_GUILD_SKILL_MAX_LEVEL")] EcGuildSkillMaxLevel = 1816,
    /// <summary>
    /// 协会培训部没有开放
    /// </summary>
    [pbr::OriginalName("EC_GUILD_TRAIN_NOT_OPEN")] EcGuildTrainNotOpen = 1817,
    /// <summary>
    /// 协会培训部已经开放
    /// </summary>
    [pbr::OriginalName("EC_GUILD_TRAIN_ALREADY_OPEN")] EcGuildTrainAlreadyOpen = 1818,
    /// <summary>
    /// 协会茶会没有开启
    /// </summary>
    [pbr::OriginalName("EC_GUILD_TEA_PARTY_NOT_OPEN")] EcGuildTeaPartyNotOpen = 1819,
    /// <summary>
    /// 协会茶会已经开启
    /// </summary>
    [pbr::OriginalName("EC_GUILD_TEA_PARTY_ALREADY_OPEN")] EcGuildTeaPartyAlreadyOpen = 1820,
    /// <summary>
    /// 协会茶会每周开启次数达到上限
    /// </summary>
    [pbr::OriginalName("EC_GUILD_TEA_PARTY_OPEN_TIMES_LIMIT")] EcGuildTeaPartyOpenTimesLimit = 1821,
    /// <summary>
    /// 部门正在升级中
    /// </summary>
    [pbr::OriginalName("EC_GUILD_BUILDING_UPGRADING")] EcGuildBuildingUpgrading = 1822,
    /// <summary>
    /// 该系统暂未开放，敬请期待
    /// </summary>
    [pbr::OriginalName("EC_IDLE_PLAY_SYS_NOT_OPEN")] EcIdlePlaySysNotOpen = 1900,
    /// <summary>
    /// 今日加速次数已用完
    /// </summary>
    [pbr::OriginalName("EC_IDLE_PLAY_ADD_TIME_EMPTY")] EcIdlePlayAddTimeEmpty = 1901,
    /// <summary>
    /// 暂无挂机奖励可领取
    /// </summary>
    [pbr::OriginalName("EC_IDLE_PLAY_NOTHING")] EcIdlePlayNothing = 1902,
    /// <summary>
    /// 挑战战斗关卡获得挂机奖励
    /// </summary>
    [pbr::OriginalName("EC_IDLE_PLAY_NO_MAINSTAGE")] EcIdlePlayNoMainstage = 1903,
    /// <summary>
    /// 该作品不存在
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_NOT_EXIST")] EcAvworksNotExist = 1950,
    /// <summary>
    /// 该名字涉嫌违规
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_INVALID_NAME")] EcAvworksInvalidName = 1951,
    /// <summary>
    /// 影音作品同时制作数量已满
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_FULL_POSITION")] EcAvworksFullPosition = 1952,
    /// <summary>
    /// 当前事件未发生
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_EVENT_UNOPEN")] EcAvworksEventUnopen = 1953,
    /// <summary>
    /// 当前事件已处理
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_EVENT_ALREADY_DONE")] EcAvworksEventAlreadyDone = 1954,
    /// <summary>
    /// 当前阶段无法进行操作
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_EVENT_OPT_ERROR")] EcAvworksEventOptError = 1955,
    /// <summary>
    /// 该阶段不允许该操作
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_STAGE_ERROR")] EcAvworksStageError = 1956,
    /// <summary>
    /// 该名粉丝礼物不存在
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_FANSGIFT_NOT_EXIST")] EcAvworksFansgiftNotExist = 1957,
    /// <summary>
    /// 未满足解锁条件
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_EXT_POS_NOT_FIT")] EcAvworksExtPosNotFit = 1958,
    /// <summary>
    /// 当前角色不符合出演要求
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_ROLE_NOT_FIT")] EcAvworksRoleNotFit = 1959,
    /// <summary>
    /// 作品已达加速上限
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_SPEED_UP_FULL")] EcAvworksSpeedUpFull = 1960,
    /// <summary>
    /// 作品事件未完成，无法完成当前章节
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_EVENT_UNDONE")] EcAvworksEventUndone = 1961,
    /// <summary>
    /// 作品尚在制作中，无法完成当前章节
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_PROGRESS_UNFULL")] EcAvworksProgressUnfull = 1962,
    /// <summary>
    /// 属性尚未选择，无法继续
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_TEMP_ATTR_EXIST")] EcAvworksTempAttrExist = 1963,
    /// <summary>
    /// 当前作品名称中未包含关键字
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_NAME_NOT_HIT_KEY")] EcAvworksNameNotHitKey = 1964,
    /// <summary>
    /// 当前演员人数不足
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_ROLE_NOT_ENOUGH")] EcAvworksRoleNotEnough = 1965,
    /// <summary>
    /// 修改文本信息超过最大限定长度
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_LENGTH_OVERFLOW")] EcAvworksLengthOverflow = 1967,
    /// <summary>
    /// 讨论值已满，不需再邀请点评
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_DISCUSS_DEGREE_OVERFLOW")] EcAvworksDiscussDegreeOverflow = 1968,
    /// <summary>
    /// 星级已满，不用再升级
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_STARLEVEL_MAX")] EcAvworksStarlevelMax = 1969,
    /// <summary>
    /// 升星使用碎片重复
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_DEBRIS_REPEAT")] EcAvworksDebrisRepeat = 1970,
    /// <summary>
    /// 升星使用碎片数量不足
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_DEBRIS_NOTENOUGH")] EcAvworksDebrisNotenough = 1971,
    /// <summary>
    /// 升星使用碎片不合法
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_DEBRIS_INVALID")] EcAvworksDebrisInvalid = 1972,
    /// <summary>
    /// 讨论值不足，暂不能升星
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_DISCUSS_DEGREE_NOTENOUGH")] EcAvworksDiscussDegreeNotenough = 1973,
    /// <summary>
    /// 当前星级不足，暂不能翻拍
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_STARLEVEL_NOT_ENOUGH")] EcAvworksStarlevelNotEnough = 1974,
    /// <summary>
    /// 同时拍摄作品数量已达到上限
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_SHOOT_FULL_POSITION")] EcAvworksShootFullPosition = 1975,
    /// <summary>
    /// 同时翻拍作品数量已达到上限
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_RESHOOT_FULL_POSITION")] EcAvworksReshootFullPosition = 1976,
    /// <summary>
    /// 作品已经存在
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_EXIST")] EcAvworksExist = 1977,
    /// <summary>
    /// 作品星级需要提升到{star}级才能宣传
    /// </summary>
    [pbr::OriginalName("EC_AVWORKS_ATTR_NEED_STAR_NOT_ENOUGH")] EcAvworksAttrNeedStarNotEnough = 1978,
    /// <summary>
    /// 尚未拥有该伙伴
    /// </summary>
    [pbr::OriginalName("EC_PARTNER_DONT_EXIST")] EcPartnerDontExist = 2000,
    /// <summary>
    /// 该名伙伴送礼次数已达上限
    /// </summary>
    [pbr::OriginalName("EC_PARTNER_SEND_GIFT_MAX")] EcPartnerSendGiftMax = 2001,
    /// <summary>
    /// 该名伙伴今日送礼次数已达上限
    /// </summary>
    [pbr::OriginalName("EC_PARTNER_ALL_SEND_GIFT_MAX")] EcPartnerAllSendGiftMax = 2002,
    /// <summary>
    /// 伙伴事件不存在
    /// </summary>
    [pbr::OriginalName("EC_PARTNER_EVENT_DONT_EXIST")] EcPartnerEventDontExist = 2003,
    /// <summary>
    /// 伙伴事件不合法
    /// </summary>
    [pbr::OriginalName("EC_PARTNER_EVENT_INVALID")] EcPartnerEventInvalid = 2004,
    /// <summary>
    /// 今日互动次数已经消耗完
    /// </summary>
    [pbr::OriginalName("EC_PARTNER_INTERACT_NO_TIMES")] EcPartnerInteractNoTimes = 2005,
    /// <summary>
    /// 伙伴合拍素材已经存在
    /// </summary>
    [pbr::OriginalName("EC_PARTNER_PHOTO_ALREADY_BUYED")] EcPartnerPhotoAlreadyBuyed = 2006,
    /// <summary>
    /// 该剧情已播放
    /// </summary>
    [pbr::OriginalName("EC_PLOT_ALREADY_PLAYED")] EcPlotAlreadyPlayed = 2100,
    /// <summary>
    /// 当前物品已达到购买上限
    /// </summary>
    [pbr::OriginalName("EC_SHOP_ITEM_LACK")] EcShopItemLack = 2200,
    /// <summary>
    /// 当前用户等级未满，无法购买
    /// </summary>
    [pbr::OriginalName("EC_SHOP_LIMIT_BY_LEVEL")] EcShopLimitByLevel = 2201,
    /// <summary>
    /// 该物品不在贩售时间段，无法购买
    /// </summary>
    [pbr::OriginalName("EC_SHOP_TIME_NOT_VALID")] EcShopTimeNotValid = 2202,
    /// <summary>
    /// 协会等级不足，不能购买
    /// </summary>
    [pbr::OriginalName("EC_SHOP_LIMIT_BY_GUILD_LEVEL")] EcShopLimitByGuildLevel = 2203,
    /// <summary>
    /// 商店刷新次数已达上限
    /// </summary>
    [pbr::OriginalName("EC_SHOP_REFRESH_TIMES_LIMITED")] EcShopRefreshTimesLimited = 2204,
    /// <summary>
    /// 商品使用性别不符合
    /// </summary>
    [pbr::OriginalName("EC_SHOP_ITEM_LIMIT_BY_SEX")] EcShopItemLimitBySex = 2205,
    /// <summary>
    /// 历史咖位等级不足，不能购买
    /// </summary>
    [pbr::OriginalName("EC_SHOP_LIMIT_BY_HISTORY_GRADE")] EcShopLimitByHistoryGrade = 2206,
    /// <summary>
    /// 手机
    /// </summary>
    [pbr::OriginalName("EC_PHONE_HOLD")] EcPhoneHold = 2300,
    /// <summary>
    /// 话题已结束
    /// </summary>
    [pbr::OriginalName("EC_PHONE_TOPIC_FINISH")] EcPhoneTopicFinish = 2301,
    /// <summary>
    /// 话题未准备好
    /// </summary>
    [pbr::OriginalName("EC_PHONE_TOPIC_NO_READY")] EcPhoneTopicNoReady = 2302,
    /// <summary>
    /// 选项不合规
    /// </summary>
    [pbr::OriginalName("EC_PHONE_TOPIC_OPTION_ILLEGAL")] EcPhoneTopicOptionIllegal = 2304,
    /// <summary>
    /// 话题不可领取
    /// </summary>
    [pbr::OriginalName("EC_PHONE_TOPIC_NO_REWARD")] EcPhoneTopicNoReward = 2305,
    /// <summary>
    /// 微博
    /// </summary>
    [pbr::OriginalName("EC_WEIBO_HOLD")] EcWeiboHold = 2400,
    /// <summary>
    /// 微博不存在
    /// </summary>
    [pbr::OriginalName("EC_WEIBO_NOT_EXIST")] EcWeiboNotExist = 2401,
    /// <summary>
    /// 微博已转发
    /// </summary>
    [pbr::OriginalName("EC_WEIBO_ALREADY_FORWARD")] EcWeiboAlreadyForward = 2402,
    /// <summary>
    /// 微博已回复
    /// </summary>
    [pbr::OriginalName("EC_WEIBO_ALREADY_COMMENT")] EcWeiboAlreadyComment = 2403,
    /// <summary>
    /// 不能是自己微博
    /// </summary>
    [pbr::OriginalName("EC_WEIBO_NO_NPC_WEIBO")] EcWeiboNoNpcWeibo = 2404,
    /// <summary>
    /// 微博还不能发布
    /// </summary>
    [pbr::OriginalName("EC_WEIBO_CANNOT_POST")] EcWeiboCannotPost = 2405,
    /// <summary>
    /// 晋级
    /// </summary>
    [pbr::OriginalName("EC_GRADE_HOLD")] EcGradeHold = 2500,
    /// <summary>
    /// 没有报名信息
    /// </summary>
    [pbr::OriginalName("EC_GRADE_NOT_REGISTER_INFO")] EcGradeNotRegisterInfo = 2501,
    /// <summary>
    /// 不能通过关卡晋级
    /// </summary>
    [pbr::OriginalName("EC_GRADE_NOT_BY_STAGE")] EcGradeNotByStage = 2502,
    /// <summary>
    /// 目标不存在 
    /// </summary>
    [pbr::OriginalName("EC_GRADE_NOT_TARGET")] EcGradeNotTarget = 2503,
    /// <summary>
    /// 挑战跨度太大
    /// </summary>
    [pbr::OriginalName("EC_GRADE_RANK_SPAN")] EcGradeRankSpan = 2504,
    /// <summary>
    /// 奖励已领取
    /// </summary>
    [pbr::OriginalName("EC_GRADE_ALREADY_REWARD")] EcGradeAlreadyReward = 2505,
    /// <summary>
    /// 该咖位没有竞技场
    /// </summary>
    [pbr::OriginalName("EC_GRADE_NO_ARENA")] EcGradeNoArena = 2506,
    /// <summary>
    /// 不在报名时段
    /// </summary>
    [pbr::OriginalName("EC_GRADE_NO_REGISTERING")] EcGradeNoRegistering = 2507,
    /// <summary>
    /// 报名人数上限
    /// </summary>
    [pbr::OriginalName("EC_GRADE_REGSITER_LIMIT")] EcGradeRegsiterLimit = 2508,
    /// <summary>
    /// 已报名
    /// </summary>
    [pbr::OriginalName("EC_GRADE_ALREADY_REGSITER")] EcGradeAlreadyRegsiter = 2509,
    /// <summary>
    /// 咖位不存在
    /// </summary>
    [pbr::OriginalName("EC_GRADE_NULL_GRADE")] EcGradeNullGrade = 2510,
    /// <summary>
    /// 不可取消
    /// </summary>
    [pbr::OriginalName("EC_GRADE_REGISTER_CANT_CANCEL")] EcGradeRegisterCantCancel = 2511,
    /// <summary>
    /// 咖位成就奖励已领取
    /// </summary>
    [pbr::OriginalName("EC_GRADE_ALREADY_ACHIEVE_REWARD")] EcGradeAlreadyAchieveReward = 2512,
    /// <summary>
    /// 未晋级该咖位
    /// </summary>
    [pbr::OriginalName("EC_GRADE_NO_IN_GRADE")] EcGradeNoInGrade = 2513,
    /// <summary>
    /// 数据已过期
    /// </summary>
    [pbr::OriginalName("EC_GRADE_DATA_EXPIRATION")] EcGradeDataExpiration = 2514,
    /// <summary>
    /// 须通过报名晋级
    /// </summary>
    [pbr::OriginalName("EC_GRADE_NEED_REGISTER")] EcGradeNeedRegister = 2515,
    /// <summary>
    /// 须先完成任务
    /// </summary>
    [pbr::OriginalName("EC_GRADE_NEED_TASK")] EcGradeNeedTask = 2516,
    /// <summary>
    /// 心动值不满足
    /// </summary>
    [pbr::OriginalName("EC_GRADE_ASSIST_NOT_ENOUGH")] EcGradeAssistNotEnough = 2517,
    /// <summary>
    /// 目标已不在该咖位
    /// </summary>
    [pbr::OriginalName("EC_GRADE_OPPONENT_NOT_FOUND")] EcGradeOpponentNotFound = 2518,
    /// <summary>
    /// 事件不可处理
    /// </summary>
    [pbr::OriginalName("EC_GRADE_TRAIN_HANDLE")] EcGradeTrainHandle = 2519,
    /// <summary>
    /// 需先完成前置采访
    /// </summary>
    [pbr::OriginalName("EC_GRADE_INTERVIEW_PREV")] EcGradeInterviewPrev = 2520,
    /// <summary>
    /// 采访已播出
    /// </summary>
    [pbr::OriginalName("EC_GRADE_INTERVIEW_FINISH")] EcGradeInterviewFinish = 2521,
    /// <summary>
    /// 聊天
    /// </summary>
    [pbr::OriginalName("EC_CHAT_HOLD")] EcChatHold = 2600,
    /// <summary>
    /// 聊天输入信息过快，请稍后再试
    /// </summary>
    [pbr::OriginalName("EC_CHAT_CD_FREEZE")] EcChatCdFreeze = 2601,
    /// <summary>
    /// 您已被聊天禁言{sec}秒
    /// </summary>
    [pbr::OriginalName("EC_CHAT_BANNED")] EcChatBanned = 2602,
    /// <summary>
    /// 聊天系统还没开放
    /// </summary>
    [pbr::OriginalName("EC_CHAT_SYSTEM_NOT_OPEN")] EcChatSystemNotOpen = 2603,
    /// <summary>
    /// 再次试镜还需等待{time}秒
    /// </summary>
    [pbr::OriginalName("EC_SWEEP_CD")] EcSweepCd = 2650,
    /// <summary>
    /// 排行
    /// </summary>
    [pbr::OriginalName("EC_RANK_HOLD")] EcRankHold = 2700,
    /// <summary>
    /// 活动
    /// </summary>
    [pbr::OriginalName("EC_ACTIVITY_HOLD")] EcActivityHold = 2800,
    /// <summary>
    /// 午夜酒吧已经投喂
    /// </summary>
    [pbr::OriginalName("EC_MIDNIGHT_PLAYBAR_FED")] EcMidnightPlaybarFed = 2801,
    /// <summary>
    /// 午夜酒吧还没投喂
    /// </summary>
    [pbr::OriginalName("EC_MIDNIGHT_PLAYBAR_NOT_FEED")] EcMidnightPlaybarNotFeed = 2802,
    /// <summary>
    /// 午夜酒吧还没揽客
    /// </summary>
    [pbr::OriginalName("EC_MIDNIGHT_PLAYBAR_WAIT")] EcMidnightPlaybarWait = 2803,
    /// <summary>
    /// 今日给ta调酒获得的羁绊度已达上限~
    /// </summary>
    [pbr::OriginalName("EC_MIDNIGHT_PLAYBAR_BONDAGE_FULL")] EcMidnightPlaybarBondageFull = 2804,
    /// <summary>
    /// 未满足最小消费次数
    /// </summary>
    [pbr::OriginalName("EC_MIDNIGHT_PLAYBAR_MINCONSUME_TIMES")] EcMidnightPlaybarMinconsumeTimes = 2805,
    /// <summary>
    /// 未满足最小伙伴羁绊度等级需求
    /// </summary>
    [pbr::OriginalName("EC_MIDNIGHT_PLAYBAR_MINBONDAGE_LEVEL")] EcMidnightPlaybarMinbondageLevel = 2806,
    /// <summary>
    /// 撸猫活动暂不开放
    /// </summary>
    [pbr::OriginalName("EC_TOUCHCAT_NOT_OPEN")] EcTouchcatNotOpen = 2821,
    /// <summary>
    /// 粉丝
    /// </summary>
    [pbr::OriginalName("EC_FANS_HOLD")] EcFansHold = 2900,
    /// <summary>
    /// 重复签约
    /// </summary>
    [pbr::OriginalName("EC_FANS_REPEAT_SIGN_CONTRACT")] EcFansRepeatSignContract = 2901,
    /// <summary>
    /// 没有核心粉丝管理
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_NOT_LEADER")] EcFansClubactivityNotLeader = 2902,
    /// <summary>
    /// 该活动不可被安排
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_CANNOT_ARRANGE")] EcFansClubactivityCannotArrange = 2903,
    /// <summary>
    /// 该活动还未完成
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_NOT_FINISH")] EcFansClubactivityNotFinish = 2904,
    /// <summary>
    /// 刷新次数不足
    /// </summary>
    [pbr::OriginalName("EC_FANS_REFRESH_TIMES_LIMIT")] EcFansRefreshTimesLimit = 2905,
    /// <summary>
    /// 需完成所有活动
    /// </summary>
    [pbr::OriginalName("EC_FANS_CANNOT_RESET")] EcFansCannotReset = 2906,
    /// <summary>
    /// 该活动可安排人数不足
    /// </summary>
    [pbr::OriginalName("EC_FANS_FC_NUM_EMPTY")] EcFansFcNumEmpty = 2907,
    /// <summary>
    /// 该活动已完成
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_FINISH")] EcFansClubactivityFinish = 2908,
    /// <summary>
    /// 该活动不存在
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_NOT_EXIST")] EcFansClubactivityNotExist = 2909,
    /// <summary>
    /// 该活动不能加速
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_CANNOT_SPEEDUP")] EcFansClubactivityCannotSpeedup = 2910,
    /// <summary>
    /// 活动都已完成
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_ALL_FINISH")] EcFansClubactivityAllFinish = 2911,
    /// <summary>
    /// 招聘人数不足
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_INVITE_LIMIT")] EcFansClubactivityInviteLimit = 2912,
    /// <summary>
    /// 沒有可刷新活动
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_NOT_REFRESH")] EcFansClubactivityNotRefresh = 2913,
    /// <summary>
    /// 黑粉丝数量过多
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_OVER_BLACKRATIO")] EcFansClubactivityOverBlackratio = 2914,
    /// <summary>
    /// 加速卡不足
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_NO_SPEEDUP_TICKET")] EcFansClubactivityNoSpeedupTicket = 2915,
    /// <summary>
    /// 刷新券不足
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_NO_REFRESH_TICKET")] EcFansClubactivityNoRefreshTicket = 2916,
    /// <summary>
    /// 粉丝数量不足
    /// </summary>
    [pbr::OriginalName("EC_FANS_SKILL_UPGRADE_NUM_LIMIT")] EcFansSkillUpgradeNumLimit = 2917,
    /// <summary>
    /// 材料不足
    /// </summary>
    [pbr::OriginalName("EC_FANS_SKILL_UPGRADE_MATERIALS_LIMIT")] EcFansSkillUpgradeMaterialsLimit = 2918,
    /// <summary>
    /// 技能等级已达到上限
    /// </summary>
    [pbr::OriginalName("EC_FANS_SKILL_UPGRADE_LEVEL_LIMIT")] EcFansSkillUpgradeLevelLimit = 2919,
    /// <summary>
    /// 活动冷却中
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_COOLDOWN_LIMIT")] EcFansClubactivityCooldownLimit = 2920,
    /// <summary>
    /// 粉丝公益活动参与次数不足
    /// </summary>
    [pbr::OriginalName("EC_FANS_BENEFIT_MAX_TIMES")] EcFansBenefitMaxTimes = 2921,
    /// <summary>
    /// 粉丝公益活动没有开启
    /// </summary>
    [pbr::OriginalName("EC_FANS_BENEFIT_NOT_OPEN")] EcFansBenefitNotOpen = 2922,
    /// <summary>
    /// 刷新券不足
    /// </summary>
    [pbr::OriginalName("EC_FANS_CLUBACTIVITY_NOT_ENOUGH_TICKET")] EcFansClubactivityNotEnoughTicket = 2923,
    /// <summary>
    /// 暂不可领取
    /// </summary>
    [pbr::OriginalName("EC_TASK_CANNOT_RECIEVE")] EcTaskCannotRecieve = 3000,
    /// <summary>
    /// 活跃度不足
    /// </summary>
    [pbr::OriginalName("EC_TASK_DAILY_LIVENESS")] EcTaskDailyLiveness = 3001,
    /// <summary>
    /// 拍摄次数不足
    /// </summary>
    [pbr::OriginalName("EC_SWEEP_TIMES_NOT_ENOUGH")] EcSweepTimesNotEnough = 3002,
    /// <summary>
    /// 已经消耗完免费招募次数
    /// </summary>
    [pbr::OriginalName("EC_RECRUIT_FREE_NONE")] EcRecruitFreeNone = 3100,
    /// <summary>
    /// 暂无免费招募次数
    /// </summary>
    [pbr::OriginalName("EC_RECRUIT_FREE_CD")] EcRecruitFreeCd = 3101,
    /// <summary>
    /// {msg}
    /// </summary>
    [pbr::OriginalName("EC_RECRUIT_DRAW_TIMES_NOT_ENOUGH")] EcRecruitDrawTimesNotEnough = 3102,
    /// <summary>
    /// 卡池暂未开放
    /// </summary>
    [pbr::OriginalName("EC_RECRUIT_TYPE_NOT_OPEN")] EcRecruitTypeNotOpen = 3103,
    /// <summary>
    /// 找不到当前类型的卡池
    /// </summary>
    [pbr::OriginalName("EC_RECRUIT_TYPE_NOTFOUND")] EcRecruitTypeNotfound = 3104,
    /// <summary>
    /// 当前课程不在上课状态
    /// </summary>
    [pbr::OriginalName("EC_COURSE_NOT_TAKING")] EcCourseNotTaking = 3150,
    /// <summary>
    /// 已经选择了其他课程
    /// </summary>
    [pbr::OriginalName("EC_COURSE_TAKING")] EcCourseTaking = 3151,
    /// <summary>
    /// 该课程不能选修
    /// </summary>
    [pbr::OriginalName("EC_COURSE_NOT_SELECTABLE")] EcCourseNotSelectable = 3152,
    /// <summary>
    /// 暂无课程可以选修
    /// </summary>
    [pbr::OriginalName("EC_COURSE_NO_LESSON")] EcCourseNoLesson = 3153,
    /// <summary>
    /// 暂无可以领取的课间休息奖励
    /// </summary>
    [pbr::OriginalName("EC_COURSE_NO_REST_REWARD")] EcCourseNoRestReward = 3154,
    /// <summary>
    /// 已达到今日选课最大上限次数
    /// </summary>
    [pbr::OriginalName("EC_COURSE_TODAY_SELECT_MAX")] EcCourseTodaySelectMax = 3155,
    /// <summary>
    /// 上课次数不足，不能升级课程
    /// </summary>
    [pbr::OriginalName("EC_COURSE_TIMES_NOTENOUGH")] EcCourseTimesNotenough = 3156,
    /// <summary>
    /// 不能升级当前正在上的课程
    /// </summary>
    [pbr::OriginalName("EC_COURSE_CANT_UPGRADE_TAKING_COURSE")] EcCourseCantUpgradeTakingCourse = 3157,
    /// <summary>
    /// 选项无效
    /// </summary>
    [pbr::OriginalName("EC_COURSE_OPTION_ERROR")] EcCourseOptionError = 3158,
    /// <summary>
    /// 你今天已经上了很多课啦，休息一下，明天再上课吧~
    /// </summary>
    [pbr::OriginalName("EC_COURSE_COURSE_MAX_LIMIT")] EcCourseCourseMaxLimit = 3159,
    /// <summary>
    /// 课程成就未达到领取条件或者已经领取
    /// </summary>
    [pbr::OriginalName("EC_COURSE_COURSE_REWARD_NOT_AVAILABLE")] EcCourseCourseRewardNotAvailable = 3160,
    /// <summary>
    /// 课程乐谱已经存在
    /// </summary>
    [pbr::OriginalName("EC_COURSE_COURSE_SHEET_EXIST")] EcCourseCourseSheetExist = 3161,
    /// <summary>
    /// 课程操作过快
    /// </summary>
    [pbr::OriginalName("EC_COURSE_COURSE_TAKE_LESSON_CD")] EcCourseCourseTakeLessonCd = 3162,
    /// <summary>
    /// 事件待处理
    /// </summary>
    [pbr::OriginalName("EC_TOWER_EVENT_HANDLING")] EcTowerEventHandling = 3200,
    /// <summary>
    /// 不是战斗关卡哦
    /// </summary>
    [pbr::OriginalName("EC_TOWER_EVENT_NOSTAGE")] EcTowerEventNostage = 3201,
    /// <summary>
    /// 不是小游戏哦
    /// </summary>
    [pbr::OriginalName("EC_TOWER_EVENT_NOLITTLEGAME")] EcTowerEventNolittlegame = 3202,
    /// <summary>
    /// 不是抽签哦
    /// </summary>
    [pbr::OriginalName("EC_TOWER_EVENT_NOLOT")] EcTowerEventNolot = 3203,
    /// <summary>
    /// 该层还未完成哦
    /// </summary>
    [pbr::OriginalName("EC_TOWER_NOT_FINISH")] EcTowerNotFinish = 3204,
    /// <summary>
    /// 重置次数不足
    /// </summary>
    [pbr::OriginalName("EC_TOWER_RESET_TIMES_LIMIT")] EcTowerResetTimesLimit = 3205,
    /// <summary>
    /// 扫荡次数不足
    /// </summary>
    [pbr::OriginalName("EC_TOWER_SWEEP_TIMES_LIMIT")] EcTowerSweepTimesLimit = 3206,
    /// <summary>
    /// 扫荡需要在起点哦
    /// </summary>
    [pbr::OriginalName("EC_TOWER_SWEEP_REQUIRE_BEGIN")] EcTowerSweepRequireBegin = 3207,
    /// <summary>
    /// 接下来的楼层需要自己前进哦
    /// </summary>
    [pbr::OriginalName("EC_TOWER_SWEEP_LIMIT")] EcTowerSweepLimit = 3208,
    /// <summary>
    /// 该物件已购买
    /// </summary>
    [pbr::OriginalName("EC_TOWER_SHOP_PRODUCT")] EcTowerShopProduct = 3209,
    /// <summary>
    /// 暂无下一层挑战
    /// </summary>
    [pbr::OriginalName("EC_TOWER_NOT_NEXT")] EcTowerNotNext = 3210,
    /// <summary>
    /// 人数需与要求相等哦
    /// </summary>
    [pbr::OriginalName("EC_TOWER_ROLE_COUNT")] EcTowerRoleCount = 3211,
    /// <summary>
    /// 通告地点未开放
    /// </summary>
    [pbr::OriginalName("EC_PLACE_NOT_OPEN")] EcPlaceNotOpen = 3301,
    /// <summary>
    /// 通告队列已满，不能解锁
    /// </summary>
    [pbr::OriginalName("EC_PLACE_UNLOCK_FULL")] EcPlaceUnlockFull = 3302,
    /// <summary>
    /// 通告未完成
    /// </summary>
    [pbr::OriginalName("EC_PLACE_FINISH_JOB_NOT_FINISH")] EcPlaceFinishJobNotFinish = 3303,
    /// <summary>
    /// 通告不在进行队列，不能加速
    /// </summary>
    [pbr::OriginalName("EC_PLACE_SPEEDUP_NOTWORKING")] EcPlaceSpeedupNotworking = 3304,
    /// <summary>
    /// 通告已完成，无需加速
    /// </summary>
    [pbr::OriginalName("EC_PLACE_SPEEDUP_JOB_FINISH")] EcPlaceSpeedupJobFinish = 3305,
    /// <summary>
    /// 通告已经在进行队列，不能安排
    /// </summary>
    [pbr::OriginalName("EC_PLACE_ARRANGE_JOB_WORKING")] EcPlaceArrangeJobWorking = 3306,
    /// <summary>
    /// 通告未通过初始面试，请先通过再继续
    /// </summary>
    [pbr::OriginalName("EC_PLACE_ARRANGE_NOT_PASS")] EcPlaceArrangeNotPass = 3307,
    /// <summary>
    /// 通告档期已满，请档期空闲再继续
    /// </summary>
    [pbr::OriginalName("EC_PLACE_ARRANGE_QUEUE_FULL")] EcPlaceArrangeQueueFull = 3308,
    /// <summary>
    /// 通告安排角色不合法
    /// </summary>
    [pbr::OriginalName("EC_PLACE_ARRANGE_ROLE_INVALID")] EcPlaceArrangeRoleInvalid = 3309,
    /// <summary>
    /// 通告安排角色重复
    /// </summary>
    [pbr::OriginalName("EC_PLACE_ARRANGE_ROLE_REPEAT")] EcPlaceArrangeRoleRepeat = 3310,
    /// <summary>
    /// 通告安排角色已在其他地点档期
    /// </summary>
    [pbr::OriginalName("EC_PLACE_ARRANGE_ROLE_CONFLICT")] EcPlaceArrangeRoleConflict = 3311,
    /// <summary>
    /// 通告安排角色不存在
    /// </summary>
    [pbr::OriginalName("EC_PLACE_ARRANGE_ROLE_NOTEXIST")] EcPlaceArrangeRoleNotexist = 3312,
    /// <summary>
    /// 通告面试已经通过，无需继续面试
    /// </summary>
    [pbr::OriginalName("EC_PLACE_CHALLENGE_ALREADY_PASS")] EcPlaceChallengeAlreadyPass = 3313,
    /// <summary>
    /// 当前通告地点正在通告，不能升级通告
    /// </summary>
    [pbr::OriginalName("EC_PLACE_UPGRADE_JOB_WORKING")] EcPlaceUpgradeJobWorking = 3314,
    /// <summary>
    /// 当前等级不足，不能升级通告
    /// </summary>
    [pbr::OriginalName("EC_PLACE_UPGRADE_LEVEL_NOT_ENOUGH")] EcPlaceUpgradeLevelNotEnough = 3315,
    /// <summary>
    /// 当前通告完成次数不足，不能升级通告
    /// </summary>
    [pbr::OriginalName("EC_PLACE_UPGRADE_TIMES_NOT_ENOUGH")] EcPlaceUpgradeTimesNotEnough = 3316,
    /// <summary>
    /// 当前通告未完成面试，不能升级通告
    /// </summary>
    [pbr::OriginalName("EC_PLACE_UPGRADE_NOT_PASS")] EcPlaceUpgradeNotPass = 3317,
    /// <summary>
    /// 今天加速完成的通告已经够多了哦~明天再来使用加速吧！
    /// </summary>
    [pbr::OriginalName("EC_PLACE_SPEEDUP_JOB_MAX")] EcPlaceSpeedupJobMax = 3318,
    /// <summary>
    /// 不在海选赛
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NOT_AUDITION")] EcFshowNotAudition = 3401,
    /// <summary>
    /// 不在淘汰赛
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NOT_KNOCKOUT")] EcFshowNotKnockout = 3402,
    /// <summary>
    /// 不在决赛
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NOT_FINAL")] EcFshowNotFinal = 3403,
    /// <summary>
    /// 暂无参加活动资格
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NOT_QULIFIED")] EcFshowNotQulified = 3404,
    /// <summary>
    /// 您已支持过对方
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_VOTED")] EcFshowVoted = 3405,
    /// <summary>
    /// 当前阶段不支持该操作
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_OPER_NOT_SUPPORT")] EcFshowOperNotSupport = 3406,
    /// <summary>
    /// 免费次数不足
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_FREE_GIFT_LIMIT")] EcFshowFreeGiftLimit = 3407,
    /// <summary>
    /// 鼓舞次数上限
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_INSPIRE_LIMIT")] EcFshowInspireLimit = 3408,
    /// <summary>
    /// 您没有参与活动
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NOT_VOTE")] EcFshowNotVote = 3409,
    /// <summary>
    /// 奖励已领取
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_REWARDED")] EcFshowRewarded = 3410,
    /// <summary>
    /// 暂不可领取
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_CANT_REWARDED")] EcFshowCantRewarded = 3411,
    /// <summary>
    /// 请您先加入平台
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_FACTION_LIMIT")] EcFshowFactionLimit = 3412,
    /// <summary>
    /// 您是队长
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_CAPTAIN")] EcFshowCaptain = 3413,
    /// <summary>
    /// 您不是队长
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NO_CAPTAIN")] EcFshowNoCaptain = 3414,
    /// <summary>
    /// 尚未加入队伍
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NOT_JOIN_TEAM")] EcFshowNotJoinTeam = 3415,
    /// <summary>
    /// 已加入队伍
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_ALREADY_JOIN_TEAM")] EcFshowAlreadyJoinTeam = 3416,
    /// <summary>
    /// 对方尚未参加活动
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NOT_CHALLENGE")] EcFshowNotChallenge = 3417,
    /// <summary>
    /// 已选择了导师
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_ALREADY_ADVISOR")] EcFshowAlreadyAdvisor = 3418,
    /// <summary>
    /// 复活人数限制
    /// </summary>
    [pbr::OriginalName("FC_FSHOW_REVIVE_LIMIT")] FcFshowReviveLimit = 3419,
    /// <summary>
    /// 请选完复活人员
    /// </summary>
    [pbr::OriginalName("FC_FSHOW_REVIVE_MORE")] FcFshowReviveMore = 3420,
    /// <summary>
    /// 不在赛后阶段
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NOT_AFTER")] EcFshowNotAfter = 3421,
    /// <summary>
    /// 您不是团队成员
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NOT_BAND_MEMBER")] EcFshowNotBandMember = 3422,
    /// <summary>
    /// 您投票次数已达上限
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_VOTE_LIMIT")] EcFshowVoteLimit = 3423,
    /// <summary>
    /// 您活跃度不足
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_LIVENESS_LIMIT")] EcFshowLivenessLimit = 3424,
    /// <summary>
    /// 您所加战队已满
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_TEAM_FULL")] EcFshowTeamFull = 3425,
    /// <summary>
    /// 还未到战斗阶段
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_NO_BATTLE")] EcFshowNoBattle = 3426,
    /// <summary>
    /// 您无需重复登上舞台
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_REPEAT_MATCH")] EcFshowRepeatMatch = 3427,
    /// <summary>
    /// 导师已被选
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_ADVISOR_PICKED")] EcFshowAdvisorPicked = 3428,
    /// <summary>
    /// 未到您选导师的时间
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_ADVISOR_NOT_NOW")] EcFshowAdvisorNotNow = 3429,
    /// <summary>
    /// 担当已被选
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_DD_CHOOSED")] EcFshowDdChoosed = 3430,
    /// <summary>
    /// 请先升级咖位
    /// </summary>
    [pbr::OriginalName("EC_FSHOW_GRADE_LIMIT")] EcFshowGradeLimit = 3431,
    /// <summary>
    /// 重复申请
    /// </summary>
    [pbr::OriginalName("EC_FRIEND_REPEATED_APPLY")] EcFriendRepeatedApply = 3501,
    /// <summary>
    /// 不可申请自己
    /// </summary>
    [pbr::OriginalName("EC_FRIEND_APPLY_SELF")] EcFriendApplySelf = 3502,
    /// <summary>
    /// 不是好友
    /// </summary>
    [pbr::OriginalName("EC_FRIEND_NOT_FRIENDSHIP")] EcFriendNotFriendship = 3503,
    /// <summary>
    /// 已在列表中
    /// </summary>
    [pbr::OriginalName("EC_FRIEND_ALREADY_FRIEND")] EcFriendAlreadyFriend = 3504,
    /// <summary>
    /// 你的好友已满，无法继续添加
    /// </summary>
    [pbr::OriginalName("EC_FRIEND_NUM_LIMIT")] EcFriendNumLimit = 3505,
    /// <summary>
    /// 该玩家好友已满，添加失败
    /// </summary>
    [pbr::OriginalName("EC_TARGET_FRIEND_NUM_LIMIT")] EcTargetFriendNumLimit = 3506,
    /// <summary>
    /// 不穿衣服是不可以出门的哦
    /// </summary>
    [pbr::OriginalName("EC_FASHION_LOSE_CLOTH")] EcFashionLoseCloth = 3511,
    /// <summary>
    /// 服装包部件不足
    /// </summary>
    [pbr::OriginalName("EC_FASHION_COMPLETE_FAIL")] EcFashionCompleteFail = 3512,
    /// <summary>
    /// 解锁了不能购买
    /// </summary>
    [pbr::OriginalName("EC_FASHION_ITEM_LOCKED")] EcFashionItemLocked = 3513,
    /// <summary>
    /// 衣服只能在商店购买
    /// </summary>
    [pbr::OriginalName("EC_FASHION_CAN_BUY_CLOTH")] EcFashionCanBuyCloth = 3514,
    /// <summary>
    /// 已经完成集齐
    /// </summary>
    [pbr::OriginalName("EC_FASHION_HAS_COMPLETE")] EcFashionHasComplete = 3515,
    /// <summary>
    /// 已经选择初始时装
    /// </summary>
    [pbr::OriginalName("EC_FASHION_SELECTED")] EcFashionSelected = 3516,
    /// <summary>
    /// 未拥有部件不能保存穿戴
    /// </summary>
    [pbr::OriginalName("EC_FASHION_NOT_PART")] EcFashionNotPart = 3517,
    /// <summary>
    /// 未拥有时装
    /// </summary>
    [pbr::OriginalName("EC_FASHION_NOT_FASHION")] EcFashionNotFashion = 3518,
    /// <summary>
    /// 放映厅未解锁
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_LOCK")] EcAvworkShowLock = 3520,
    /// <summary>
    /// 作品未完成初次拍摄无法上映
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_NOT_SHOOT")] EcAvworkShowNotShoot = 3521,
    /// <summary>
    /// 放映厅不存在
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_NOT_HALL")] EcAvworkShowNotHall = 3522,
    /// <summary>
    /// 当前放映厅人数已满，无法进入
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_HALL_FULL")] EcAvworkShowHallFull = 3523,
    /// <summary>
    /// 今日点赞次数已达上限
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_ENJOY_LIMIT")] EcAvworkShowEnjoyLimit = 3524,
    /// <summary>
    /// 分享他人零食冷却中
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_SNACK_CD")] EcAvworkShowSnackCd = 3525,
    /// <summary>
    /// 只有放映厅主人才能添加零食
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_ADDSNACK_MUSTOWNER")] EcAvworkShowAddsnackMustowner = 3526,
    /// <summary>
    /// 零食数量达到上限，无法添加
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_SNACK_NUM_LIMIT")] EcAvworkShowSnackNumLimit = 3527,
    /// <summary>
    /// 这是你自己添加的零食
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_GETSNACK_NOTONWER")] EcAvworkShowGetsnackNotonwer = 3528,
    /// <summary>
    /// 当前放映厅暂未添加零食
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_NONE_SNACK")] EcAvworkShowNoneSnack = 3529,
    /// <summary>
    /// 当前零食剩余可分享次数不足
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_SNACK_TIMES_LIMIT")] EcAvworkShowSnackTimesLimit = 3530,
    /// <summary>
    /// NPC不存在
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_NOT_NPC")] EcAvworkShowNotNpc = 3531,
    /// <summary>
    /// 留言字数过长
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_MESSAGE_LEN_LIMIT")] EcAvworkShowMessageLenLimit = 3532,
    /// <summary>
    /// 不能给自己放映厅点赞
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_NOT_ENJOY_SELF")] EcAvworkShowNotEnjoySelf = 3533,
    /// <summary>
    /// 不能对同一作品重复点赞
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_ENJOY_REPEAT")] EcAvworkShowEnjoyRepeat = 3534,
    /// <summary>
    /// 预上映阶段才可以添加作品
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_NOT_SETWORK")] EcAvworkShowNotSetwork = 3535,
    /// <summary>
    /// 放映厅主人才能进行操作
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_NOTOWNER")] EcAvworkShowNotowner = 3536,
    /// <summary>
    /// 更换的目标位置没有零食
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_CHANGE_SNACK_NOT_EXIT")] EcAvworkShowChangeSnackNotExit = 3537,
    /// <summary>
    /// 只有在预上映阶段才可以操作
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_NOT_PRESHOW")] EcAvworkShowNotPreshow = 3538,
    /// <summary>
    /// 上映期间无法更换已经消耗过的零食
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_NOT_CHANGE_FIRST_SNACK")] EcAvworkShowNotChangeFirstSnack = 3539,
    /// <summary>
    /// 重复解锁
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_UNLOCK")] EcAvworkShowUnlock = 3540,
    /// <summary>
    /// 活动中无法操作
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_OPENING")] EcAvworkShowOpening = 3541,
    /// <summary>
    /// 无法重复上映作品
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_SETED_WORK")] EcAvworkShowSetedWork = 3542,
    /// <summary>
    /// 已经分享过当前零食了，不要太贪心哦
    /// </summary>
    [pbr::OriginalName("EC_AVWORK_SHOW_GOT_SNACK")] EcAvworkShowGotSnack = 3543,
    /// <summary>
    /// 活动未开启
    /// </summary>
    [pbr::OriginalName("EC_ACTIVITY_NOT_OPEN")] EcActivityNotOpen = 3544,
    /// <summary>
    /// 已经在队伍中
    /// </summary>
    [pbr::OriginalName("EC_TEAM_IS_IN_TEAM")] EcTeamIsInTeam = 3550,
    /// <summary>
    /// 没有队伍
    /// </summary>
    [pbr::OriginalName("EC_TEAM_NOT_TEAM")] EcTeamNotTeam = 3551,
    /// <summary>
    /// 不是队长，无法操作
    /// </summary>
    [pbr::OriginalName("EC_TEAM_NOT_LEADER")] EcTeamNotLeader = 3552,
    /// <summary>
    /// 对方不在队伍中
    /// </summary>
    [pbr::OriginalName("EC_TEAM_NOT_IN_TEAM")] EcTeamNotInTeam = 3553,
    /// <summary>
    /// 等级不足
    /// </summary>
    [pbr::OriginalName("EC_TEAM_LEVEL_LIMIT")] EcTeamLevelLimit = 3554,
    /// <summary>
    /// 队伍人已经满
    /// </summary>
    [pbr::OriginalName("EC_TEAM_FULL")] EcTeamFull = 3555,
    /// <summary>
    /// 不在申请列表中
    /// </summary>
    [pbr::OriginalName("EC_TEAM_NOT_IN_APPLY")] EcTeamNotInApply = 3556,
    /// <summary>
    /// 将{name}踢出队伍
    /// </summary>
    [pbr::OriginalName("EC_TEAM_KNICK")] EcTeamKnick = 3557,
    /// <summary>
    /// 被踢出队伍
    /// </summary>
    [pbr::OriginalName("EC_TEAM_BE_KNICK")] EcTeamBeKnick = 3558,
    /// <summary>
    /// 成为队长
    /// </summary>
    [pbr::OriginalName("EC_TEAM_BE_LEADER")] EcTeamBeLeader = 3559,
    /// <summary>
    /// 将队长转移给{name}
    /// </summary>
    [pbr::OriginalName("EC_TEAM_TRANSFER_LEADER")] EcTeamTransferLeader = 3560,
    /// <summary>
    /// {name}退出队伍
    /// </summary>
    [pbr::OriginalName("EC_TEAM_QUIT")] EcTeamQuit = 3561,
    /// <summary>
    /// 对方离线状态
    /// </summary>
    [pbr::OriginalName("EC_TEAM_TARGET_OFFLINE")] EcTeamTargetOffline = 3562,
    /// <summary>
    /// 等级不足
    /// </summary>
    [pbr::OriginalName("EC_TEAM_TYPE_LEVEL_LIMIT")] EcTeamTypeLevelLimit = 3563,
    /// <summary>
    /// 不在邀请队列中
    /// </summary>
    [pbr::OriginalName("EC_TEAM_NOT_IN_INVITE_LIST")] EcTeamNotInInviteList = 3564,
    /// <summary>
    /// 队伍正在进行副本
    /// </summary>
    [pbr::OriginalName("EC_TEAM_IS_IN_FB")] EcTeamIsInFb = 3565,
    /// <summary>
    /// 职位已经满人
    /// </summary>
    [pbr::OriginalName("EC_TEAM_POST_FULL")] EcTeamPostFull = 3566,
    /// <summary>
    /// 角色重复
    /// </summary>
    [pbr::OriginalName("EC_TEAM_REPEATED_ROLE")] EcTeamRepeatedRole = 3567,
    /// <summary>
    /// 已经放置过角色
    /// </summary>
    [pbr::OriginalName("EC_TEAM_HAS_EMBATTLE")] EcTeamHasEmbattle = 3568,
    /// <summary>
    /// 队长不能更换队员的角色
    /// </summary>
    [pbr::OriginalName("EC_TEAM_LEADER_NOT_CHANGE")] EcTeamLeaderNotChange = 3569,
    /// <summary>
    /// 队员只能更换一个角色
    /// </summary>
    [pbr::OriginalName("EC_TEAM_MEMBER_CHANGE_ONE")] EcTeamMemberChangeOne = 3570,
    /// <summary>
    /// 队员不能更换别人的角色
    /// </summary>
    [pbr::OriginalName("EC_TEAM_MEMBER_CHANGE_SELF")] EcTeamMemberChangeSelf = 3571,
    /// <summary>
    /// 没有准备无法操作
    /// </summary>
    [pbr::OriginalName("EC_TEAM_NOT_READY")] EcTeamNotReady = 3572,
    /// <summary>
    /// 已经准备无法操作
    /// </summary>
    [pbr::OriginalName("EC_TEAM_IS_READY")] EcTeamIsReady = 3573,
    /// <summary>
    /// 上阵角色数量不足
    /// </summary>
    [pbr::OriginalName("EC_TEAM_EMBATTLE_NUM")] EcTeamEmbattleNum = 3574,
    /// <summary>
    /// 不在副本中
    /// </summary>
    [pbr::OriginalName("EC_TEAM_NOT_IN_PLAY")] EcTeamNotInPlay = 3575,
    /// <summary>
    /// 副本类型错误
    /// </summary>
    [pbr::OriginalName("EC_TEAM_PLAY_TYPE_ERROR")] EcTeamPlayTypeError = 3576,
    /// <summary>
    /// 顶替职位过期
    /// </summary>
    [pbr::OriginalName("EC_TEAM_PLAY_REPLACE_PAST")] EcTeamPlayReplacePast = 3577,
    /// <summary>
    /// 次数不足
    /// </summary>
    [pbr::OriginalName("EC_TEAM_PLAY_REWARD_TIMES")] EcTeamPlayRewardTimes = 3578,
    /// <summary>
    /// 该队伍正在商务表演中，请稍后再试
    /// </summary>
    [pbr::OriginalName("EC_TEAM_PLAY_IS_FIGHTING")] EcTeamPlayIsFighting = 3579,
    /// <summary>
    /// 该玩家已有队伍
    /// </summary>
    [pbr::OriginalName("EC_TEAM_TARGET_IN_TEAM")] EcTeamTargetInTeam = 3580,
    /// <summary>
    /// 人数不足无法开始
    /// </summary>
    [pbr::OriginalName("EC_TEAM_LACK_MEMBER")] EcTeamLackMember = 3581,
    /// <summary>
    /// 队伍正准备进入副本中
    /// </summary>
    [pbr::OriginalName("EC_TEAM_IS_WAITING_CONFIRM")] EcTeamIsWaitingConfirm = 3582,
    /// <summary>
    /// 正在进行罢免流程
    /// </summary>
    [pbr::OriginalName("EC_TEAM_RELIEVING")] EcTeamRelieving = 3583,
    /// <summary>
    /// 已经提交罢免选择
    /// </summary>
    [pbr::OriginalName("EC_TEAM_RELIEVE_ANSWERED")] EcTeamRelieveAnswered = 3584,
    /// <summary>
    /// 罢免已经结束
    /// </summary>
    [pbr::OriginalName("EC_TEAM_RELIEVE_TIMEOUT")] EcTeamRelieveTimeout = 3585,
    /// <summary>
    /// 不是罢免的参与者
    /// </summary>
    [pbr::OriginalName("EC_TEAM_RELIEVE_NOT_JOINER")] EcTeamRelieveNotJoiner = 3586,
    /// <summary>
    /// 罢免频率太高
    /// </summary>
    [pbr::OriginalName("EC_TEAM_RELIEVE_CD")] EcTeamRelieveCd = 3587,
    /// <summary>
    /// 特殊副本无法创建队伍
    /// </summary>
    [pbr::OriginalName("EC_TEAM_SPECIAL_PLAY")] EcTeamSpecialPlay = 3588,
    /// <summary>
    /// 更换阵容角色失败
    /// </summary>
    [pbr::OriginalName("EC_TEAM_CHANGE_EMBATTLE_FAIL")] EcTeamChangeEmbattleFail = 3589,
    /// <summary>
    /// 该副本无法进行单人挑战
    /// </summary>
    [pbr::OriginalName("EC_TEAM_TEAMPLAY_SOLO_FAIL")] EcTeamTeamplaySoloFail = 3590,
    /// <summary>
    /// 邀请cd中
    /// </summary>
    [pbr::OriginalName("EC_TEAM_WORLD_INVITE_CD")] EcTeamWorldInviteCd = 3591,
    /// <summary>
    /// 队友处于挂起中
    /// </summary>
    [pbr::OriginalName("EC_TEAM_MEMBER_HANG_UP")] EcTeamMemberHangUp = 3592,
    /// <summary>
    /// 所有队员均已归队
    /// </summary>
    [pbr::OriginalName("EC_TEAM_NO_HANG_UP")] EcTeamNoHangUp = 3593,
    /// <summary>
    /// 召回过于频繁
    /// </summary>
    [pbr::OriginalName("EC_TEAM_CALLBACK_CD")] EcTeamCallbackCd = 3594,
    /// <summary>
    /// 加入队伍失败
    /// </summary>
    [pbr::OriginalName("EC_TEAM_JOIN_FAIL")] EcTeamJoinFail = 3595,
    /// <summary>
    /// 公演未开启
    /// </summary>
    [pbr::OriginalName("EC_TEAM_PLAY_NOT_OPEN")] EcTeamPlayNotOpen = 3596,
    /// <summary>
    /// 商演未开启
    /// </summary>
    [pbr::OriginalName("EC_TEAM_HANGING_NOT_OPEN")] EcTeamHangingNotOpen = 3597,
    /// <summary>
    /// 没有进行中的挑战
    /// </summary>
    [pbr::OriginalName("EC_WAR_NOT_CHALLENGE")] EcWarNotChallenge = 3600,
    /// <summary>
    /// 挑战不存在
    /// </summary>
    [pbr::OriginalName("EC_WAR_NOT_EXIST")] EcWarNotExist = 3601,
    /// <summary>
    /// 挑战已结束
    /// </summary>
    [pbr::OriginalName("EC_WAR_HAS_FINISH")] EcWarHasFinish = 3602,
    /// <summary>
    /// 技能尚未准备好
    /// </summary>
    [pbr::OriginalName("EC_WAR_SKILL_CAST")] EcWarSkillCast = 3603,
    /// <summary>
    /// 尚未足够
    /// </summary>
    [pbr::OriginalName("EC_WAR_MISS_QTE")] EcWarMissQte = 3604,
    /// <summary>
    /// 没有指定卡牌，无法安装
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_NOT_CARD")] EcTraintoolNotCard = 3620,
    /// <summary>
    /// 等级不足
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_LEVEL_LIMIT")] EcTraintoolLevelLimit = 3621,
    /// <summary>
    /// 已经安装
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_IS_UNLOCK")] EcTraintoolIsUnlock = 3622,
    /// <summary>
    /// 没有安装
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_LOCK")] EcTraintoolLock = 3623,
    /// <summary>
    /// 已通关
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_PASS")] EcTraintoolPass = 3624,
    /// <summary>
    /// 无法助战
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_CANT_ASSIST")] EcTraintoolCantAssist = 3625,
    /// <summary>
    /// 没有指定职业，无法挑战
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_PROF_LIMIT")] EcTraintoolProfLimit = 3627,
    /// <summary>
    /// 没有指定卡牌，无法挑战
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_CARD_LIMIT")] EcTraintoolCardLimit = 3628,
    /// <summary>
    /// 指定上阵人数不足，无法挑战
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_NUM_LIMIT")] EcTraintoolNumLimit = 3629,
    /// <summary>
    /// 助战次数不足
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_ASSIST_TIMES_LIMIT")] EcTraintoolAssistTimesLimit = 3630,
    /// <summary>
    /// 好友助战次数不足
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_ASSIST_FIREND_LIMIT")] EcTraintoolAssistFirendLimit = 3631,
    /// <summary>
    /// 挑战cd中
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_CHALLENGE_CD")] EcTraintoolChallengeCd = 3632,
    /// <summary>
    /// 没有好友助战
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_NO_FRIEND_ASSIST")] EcTraintoolNoFriendAssist = 3633,
    /// <summary>
    /// 没有角色无法添加
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_NO_ROLE")] EcTraintoolNoRole = 3634,
    /// <summary>
    /// 主角无法助战
    /// </summary>
    [pbr::OriginalName("EC_TRAINTOOL_NOT_PLAYER")] EcTraintoolNotPlayer = 3635,
    /// <summary>
    /// 没有解锁自定义方案
    /// </summary>
    [pbr::OriginalName("EC_FASHION_NOT_UNLOCK_SCHEME")] EcFashionNotUnlockScheme = 3650,
    /// <summary>
    /// 没有自定义方案
    /// </summary>
    [pbr::OriginalName("EC_FASHION_HAVE_NOT_SCHEME")] EcFashionHaveNotScheme = 3651,
    /// <summary>
    /// 时装部位有重复
    /// </summary>
    [pbr::OriginalName("EC_FASHION_PART_REPEAT")] EcFashionPartRepeat = 3652,
    /// <summary>
    /// 已经解锁自定义方案
    /// </summary>
    [pbr::OriginalName("EC_FASHION_UNLOCKED_SCHEME")] EcFashionUnlockedScheme = 3653,
    /// <summary>
    /// 已解锁所有方案
    /// </summary>
    [pbr::OriginalName("EC_FASHION_UNLOCK_ALL_SCHEME")] EcFashionUnlockAllScheme = 3654,
    /// <summary>
    /// 时装包不存在
    /// </summary>
    [pbr::OriginalName("EC_FASHION_NOT_PACKAGE")] EcFashionNotPackage = 3655,
    /// <summary>
    /// 已经领取奖励
    /// </summary>
    [pbr::OriginalName("EC_FASHION_REWARDED")] EcFashionRewarded = 3656,
    /// <summary>
    /// 品牌已经达到最大等级
    /// </summary>
    [pbr::OriginalName("EC_FASHION_BRAND_LEVEL_LIMIT")] EcFashionBrandLevelLimit = 3657,
    /// <summary>
    /// 升级品牌积分不足
    /// </summary>
    [pbr::OriginalName("EC_FASHION_BRAND_SCORE_LESS")] EcFashionBrandScoreLess = 3658,
    /// <summary>
    /// 选择初始时装性别错误
    /// </summary>
    [pbr::OriginalName("EC_FASHION_SELECT_SEX_FAIL")] EcFashionSelectSexFail = 3659,
    /// <summary>
    /// 自定义方案名字过长
    /// </summary>
    [pbr::OriginalName("EC_FASHION_SCHEME_NAME_LEN")] EcFashionSchemeNameLen = 3660,
    /// <summary>
    /// 时装不足
    /// </summary>
    [pbr::OriginalName("EC_FASHION_NOT_ENOUGH")] EcFashionNotEnough = 3661,
    /// <summary>
    /// 没有制作图纸
    /// </summary>
    [pbr::OriginalName("EC_FASHION_NOT_MAKEPAPER")] EcFashionNotMakepaper = 3662,
    /// <summary>
    /// 时装关卡不存在
    /// </summary>
    [pbr::OriginalName("EC_FASHION_STAGE_NOT_STAGE")] EcFashionStageNotStage = 3680,
    /// <summary>
    /// 时装关卡前置剧情未完成
    /// </summary>
    [pbr::OriginalName("EC_FASHION_STAGE_PLOT_LIMIT")] EcFashionStagePlotLimit = 3681,
    /// <summary>
    /// 您已拥有该称号
    /// </summary>
    [pbr::OriginalName("EC_TITLE_ACTIVED")] EcTitleActived = 3700,
    /// <summary>
    /// 称号已使用
    /// </summary>
    [pbr::OriginalName("EC_TITLE_USED")] EcTitleUsed = 3701,
    /// <summary>
    /// 称号不足
    /// </summary>
    [pbr::OriginalName("EC_TITLE_NOT_ENOUGH")] EcTitleNotEnough = 3702,
    /// <summary>
    /// 称号未激活
    /// </summary>
    [pbr::OriginalName("EC_TITLE_NOT_TITLE")] EcTitleNotTitle = 3703,
    /// <summary>
    /// 其他
    /// </summary>
    [pbr::OriginalName("EC_OTHER")] EcOther = 4000,
  }

  #endregion

}

#endregion Designer generated code
